# 100 numpy excellent problems with soution
Source: https://github.com/SimmiSheetalJain/Python-Practice/blob/main/Python%20Practice/100_Numpy_exercises(without%20solution).ipynb

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.24.3'

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
arr.size


10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
np.add?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
arr=np.arange(10,49)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
arr[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.randint(0,27,size=(3,3,3))

array([[[25, 14, 20],
        [ 3, 10, 15],
        [11,  8, 12]],

       [[23, 14, 10],
        [25, 12, 19],
        [21, 17,  2]],

       [[18, 10,  6],
        [ 0, 20, 10],
        [13, 13, 10]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
arr1=np.random.randint(1200,1299,size=(10,10))
print(arr1.min())
print(arr1.max())

1201
1298


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
arr2 = np.random.randint(23,56,size=(30))
format(arr2.mean(),".2f")

'38.70'

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
arr3=np.ones(25).reshape(5,5)
arr3[1:-1,1:-1]=0
print(arr3)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
arr1=np.random.randint(1200,1299,size=(10,10))
arr1[:1,:]=arr1[:,:1]=arr1[:,len(arr1)-1:]=arr1[len(arr1)-1:,:]=0
arr1

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0, 1280, 1259, 1214, 1210, 1265, 1276, 1281, 1221,    0],
       [   0, 1272, 1202, 1273, 1258, 1215, 1278, 1277, 1226,    0],
       [   0, 1221, 1215, 1257, 1298, 1231, 1262, 1294, 1248,    0],
       [   0, 1298, 1224, 1237, 1285, 1206, 1247, 1209, 1278,    0],
       [   0, 1215, 1288, 1238, 1210, 1255, 1222, 1268, 1290,    0],
       [   0, 1223, 1222, 1288, 1244, 1201, 1224, 1205, 1249,    0],
       [   0, 1233, 1243, 1276, 1205, 1256, 1238, 1234, 1248,    0],
       [   0, 1287, 1242, 1237, 1234, 1288, 1282, 1268, 1285,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
#Beginner approach
arr3=np.zeros(25).reshape(5,5)
for i,j in zip(range(0,len(arr3)),range(1,len(arr3))):
    arr3[j][i]=j
print(arr3)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [20]:
#Numpy approach 
arr= np.zeros((5,5))
np.fill_diagonal(arr[1:],[1,2,3,4])
print(arr)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
arr= np.zeros((8,8))
arr[::2,::2]=1
arr[1::2, 1::2] = 1 
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [22]:
#My answer after watching fourth part of matrix
arr=np.array([[list(range(0,8))]*7]*6)
arr[1][5][3]=100
print(arr)

[[[  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]]

 [[  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2 100   4   5   6   7]
  [  0   1   2   3   4   5   6   7]]

 [[  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]]

 [[  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [27]:
arr=np.array([[1,0],[0,1]])
check_board=np.tile(arr,(4,4))
check_board

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [16]:
import numpy as np 
import matplotlib.pyplot as plt
orginal_matrix = np.random.rand(5,5)
mean = np.mean(orginal_matrix)
std_dev = np.std(orginal_matrix)
normalized_matrix = (orginal_matrix - mean)/ std_dev
print(" Orginal Matrix\n ",  orginal_matrix)
print(" Normalized Matrix\n ",  normalized_matrix)

 Orginal Matrix
  [[0.13992156 0.51970335 0.30238302 0.10855903 0.04627473]
 [0.17956199 0.29669616 0.62959021 0.16254368 0.07857205]
 [0.71052995 0.44463907 0.11814946 0.7329878  0.05761887]
 [0.70279655 0.45704813 0.31235217 0.96990882 0.57358658]
 [0.808817   0.76621215 0.32035292 0.22154408 0.84675482]]
 Normalized Matrix
  [[-0.9998956   0.35457227 -0.42048701 -1.11174811 -1.33388116]
 [-0.8585205  -0.44076886  0.74647686 -0.91921526 -1.21869479]
 [ 1.03514333  0.08686022 -1.07754444  1.11523786 -1.29342299]
 [ 1.00756267  0.13111636 -0.38493268  1.96020179  0.54674344]
 [ 1.38567792  1.23373042 -0.3563985  -0.70879403  1.5209808 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [29]:
import numpy as np
rgba = np.dtype([('r', np.uint32),('g', np.uint32),('b', np.uint32),('a', np.uint32)])
value = np.array([(250, 0, 0, 255),
                  (0, 255, 0, 255),
                  (0, 0, 255, 255),
                  (255, 255, 255, 255)], dtype =rgba)
print(value)

[(250,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)
 (255, 255, 255, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [31]:
import numpy as np
arr1 = np.random.rand(5,3)
arr2 = np.random.rand(3,2)
print(arr1)
print(arr2)
arr1@arr2

[[0.74003165 0.54958208 0.45504712]
 [0.72578545 0.52546562 0.28527561]
 [0.47160572 0.9953643  0.22950678]
 [0.2165867  0.63534404 0.96645403]
 [0.61107722 0.93583567 0.39700595]]
[[0.62524871 0.03874115]
 [0.19014238 0.14296761]
 [0.31316516 0.71419194]]


array([[0.70970758, 0.4322331 ],
       [0.64304808, 0.30698386],
       [0.55600533, 0.32448729],
       [0.55888612, 0.78945812],
       [0.6843457 , 0.44100647]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [43]:
arr = np.random.randint(4,12,25)
arr = np.where( (3<arr) & (arr<8), -arr, arr)
print(arr)

[-4 -6  9  9 -4 -4 11 -4  8 -5 11 -5 -4  9  9 11 10 10 -6 11 10 11 -7  8
 -5]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [45]:
'''This is the sum() function of the core python. 
Thus, the second argument represents the initial value of the sum 
function. Hence, sum=-1+0+1+2+3+4 = 9 '''
print(sum(range(5),-1))
from numpy import *
'''After importing numpy, we are usign sum() used which is there in
numpy. And the second argument represent the axis i.e. sum along 
axis 1'''
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [13]:
import numpy as np
z=np.arange(5)
print(" z : ", z)
#Expression 1:it does N^N where N is an element of the vector z
print("Result of expression 1: ", z**z)
#Expression 2: Expression is evaluated on bitwise operator and from left to right.
print("Result of expression 2: ",2 << z >> 2)
#Exoression 3: 
print("Result of expression 3: ", z<-z)
#Expression 4: converts all elment into a complex number
print("Result of expression 4: ", 1j*z)
#Expression 5: 
print("Result of expression 5: ",z/1/1)
#Expression 6: This is an ambiguous expression and results in an error
print("Result of expression 5: ",z<z<z)

 z :  [0 1 2 3 4]
Result of expression 1:  [  1   1   4  27 256]
Result of expression 2:  [0 1 2 4 8]
Result of expression 3:  [False False False False False]
Result of expression 4:  [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
Result of expression 5:  [0. 1. 2. 3. 4.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [32]:
np.array(0) / np.array(0)       #Divide By Zero (Runtime Error)
np.array(0) // np.array(0)      #Divide By Zero (Runtime Error)
'''Convert nan into minimum integer value that the data type can represent and then back to float(whihc results in a 
a negative value)'''
np.array([np.nan]).astype(int).astype(float) 

C:\Users\user\AppData\Local\Temp\ipykernel_5700\4124992270.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)       #Divide By Zero (Runtime Error)
C:\Users\user\AppData\Local\Temp\ipykernel_5700\4124992270.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)      #Divide By Zero (Runtime Error)
C:\Users\user\AppData\Local\Temp\ipykernel_5700\4124992270.py:5: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [51]:
import numpy as np
arr =  np.random.randn(10)
print(arr)
rounded_arr = np.ceil(arr[arr>=0])
rounded_arr1 = np.floor(arr[arr < 0])
final =  np.concatenate([rounded_arr,rounded_arr1])
print(final)

[-1.74641099 -1.3656557  -0.44242372  0.34476221 -0.05118213  0.66537005
 -0.61676653 -1.06245415 -0.42980825  0.87076257]
[ 1.  1.  1. -2. -2. -1. -1. -1. -2. -1.]










#### 30. How to find common values between two arrays? (★☆☆)

In [70]:
arr1 = np.random.randint(12,20,25)
arr2 = np.random.randint(12,20,25)
arr3 = arr1[np.isin(arr1, arr2)]
print("Array1 : ", arr1, "Array 2: ", arr2,sep="\n")
print("Common Element between the two arrays : ",arr3)

Array1 : 
[12 19 17 13 14 13 13 15 12 16 18 19 16 19 12 12 17 18 16 13 12 19 17 13
 14]
Array 2: 
[12 14 15 18 16 15 16 19 18 15 19 16 18 12 19 12 15 15 14 15 17 12 13 16
 13]
Common Element between the two arrays :  [12 19 17 13 14 13 13 15 12 16 18 19 16 19 12 12 17 18 16 13 12 19 17 13
 14]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [72]:
import numpy as np 
np.seterr(all='ignore')

#Reset it 
np.seterr(all=None)

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [74]:
bool(np.sqrt(-1 == np.emath.sqrt(-1)))

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [85]:
import numpy as np
today =  np.datetime64('today','D')
yd = today - np.timedelta64(1,'D')
tm = today + np.timedelta64(1,'D')
print("Yesterday's Date :", yd)
print(" Today's Date : ", today)
print("Tomorrow's Date : ", tm)

Yesterday's Date : 2024-02-17
 Today's Date :  2024-02-18
Tomorrow's Date :  2024-02-19


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [9]:
import numpy as np
import datetime

year = eval(input("Enter the year : "))
month = eval(input("Enter the month (in integer format) : "))

if 0 < month < 13:
    start_date = datetime.date(year, month, 1)
    num_days = (start_date.replace(month=start_date.month % 12 + 1, day=1) - start_date).days
    dates = [start_date + datetime.timedelta(days=i) for i in range(num_days)]

    for date in dates:
        print(date)
else:
    print("There is no such month in a year")

Enter the year : 2024
Enter the month (in integer format) : 2
2024-02-01
2024-02-02
2024-02-03
2024-02-04
2024-02-05
2024-02-06
2024-02-07
2024-02-08
2024-02-09
2024-02-10
2024-02-11
2024-02-12
2024-02-13
2024-02-14
2024-02-15
2024-02-16
2024-02-17
2024-02-18
2024-02-19
2024-02-20
2024-02-21
2024-02-22
2024-02-23
2024-02-24
2024-02-25
2024-02-26
2024-02-27
2024-02-28
2024-02-29


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [30]:
import numpy as np
A = np.array([4,5,3,3,3])
print(A)
B = np.array([5,9,5,8,9])
print(B)
A = A.astype(np.float64)
B = B.astype(np.float64)
A = - (A/2)
A = -2*A*A + B*A
print(A)

[4 5 3 3 3]
[5 9 5 8 9]
[-18.  -35.  -12.  -16.5 -18. ]


In [31]:
A = np.array([4,5,3,3,3])
print(A)
B = np.array([5,9,5,8,9])
print(B)
#For verification let's see the result is same or not
print(((A+B)*(-A/2)))

[4 5 3 3 3]
[5 9 5 8 9]
[-18.  -35.  -12.  -16.5 -18. ]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [49]:
#Way 1 : Using manual logic 
arr=np.linspace(3,40,6)
print(arr)
dummy = arr.astype(np.int32)
dummy= arr - dummy
arr=arr-dummy
print(arr)

[ 3.  10.4 17.8 25.2 32.6 40. ]
[ 3. 10. 17. 25. 32. 40.]


In [50]:
#Way2 : Using floor or ceil function 
arr = np.linspace(3,40,6)
print(np.floor(arr))

[ 3. 10. 17. 25. 32. 40.]


In [52]:
#Way3 : Using trunc() function 
arr = np.linspace(3,40,6)
print(np.trunc(arr))

[ 3. 10. 17. 25. 32. 40.]


In [53]:
#Way :  round()
arr = np.linspace(3,40,6)
print(np.round(arr))

[ 3. 10. 18. 25. 33. 40.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [2]:
import numpy as np
arr =  np.random.randint(0,4,25).reshape(5,5)
print(arr)

[[0 1 2 0 1]
 [1 3 2 0 1]
 [3 2 1 3 2]
 [3 0 1 2 1]
 [0 0 2 1 2]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [18]:
def generateAnArray(size):
    num = 1
    try:
        while num<=size:
            yield int(input(f"Enter your element number {num} : "))
            num+=1
    except Exception as e:
        print(e)

In [22]:
import numpy as np
gen = generateAnArray(5)
array=np.array(list(gen))
print(array)

Enter your element number 1 : 45
Enter your element number 2 : 12
Enter your element number 3 : 13
Enter your element number 4 : 14
Enter your element number 5 : 12
[45 12 13 14 12]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [24]:
arr=np.random.rand(10)
arr

array([0.9573707 , 0.46834775, 0.74307731, 0.23160261, 0.8294519 ,
       0.28631227, 0.20980612, 0.39762921, 0.85912255, 0.91678172])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [26]:
arr = np.random.randint(1,100,10)
arr.sort()
arr

array([ 5, 13, 15, 17, 27, 43, 59, 60, 62, 68])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [35]:
import numpy as np 
arr = np.random.randint(1,101,10)
print("The element of the array are : ", arr)
result = np.add.reduce(arr)
print("The sum of all the element of the array is result:", result)

The element of the array are :  [21 39  8 31 48 18 43 86 32 16]
The sum of all the element of the array is result: 342


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [73]:
import numpy as np
A = np.random.randint(1,5,2)
B = np.random.randint(1,4,2)
flag = True
print(f"A = {A}",f"B = {B}",sep = "\n")
for a,b in zip(A,B):
    if a!=b:
        flag = False
        break
if flag==True:
    print("The arrays are same")
else:
    print("The arrays are not same")

A = [1 3]
B = [2 3]
The arrays are not same


#### 43. Make an array immutable (read-only) (★★☆)

In [80]:
import numpy as np
arr = np.array([12,34,54,32,43])
immutable_array = arr.view()
immutable_array.flags.writeable=False
try:
    immutable_array[2] = 4
except Exception as e:
    print(e)

assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [92]:
import numpy as np
import math
cartesian_coordinates = np.random.randint(11,31,20).reshape(10,2)
polar_coordinates = []
print("Cartesian Coordinates: ")
for co in cartesian_coordinates:
    print(co)
for co in cartesian_coordinates:
    r = math.sqrt((co[0])**2+(co[1])**2)
    theta = math.atan2(co[1],co[0])
    polar_coordinates.append([r,theta])
print("Polar Coordinates: ")
for co in polar_coordinates:
    print(co)

Cartesian Coordinates: 
[16 13]
[14 15]
[25 30]
[22 12]
[19 16]
[23 24]
[23 12]
[12 24]
[17 29]
[23 17]
Polar Coordinates: 
[20.615528128088304, 0.6823165548747481]
[20.518284528683193, 0.8198672643969563]
[39.05124837953327, 0.8760580505981934]
[25.059928172283335, 0.4993467216801301]
[24.839484696748443, 0.6998928697192437]
[33.24154027718932, 0.8066715494215095]
[25.942243542145693, 0.48088728019533583]
[26.832815729997478, 1.1071487177940904]
[33.61547262794322, 1.0405805540182667]
[28.600699292150182, 0.636508215787951]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [97]:
import numpy as np
arr =  np.random.randint(1,100,10)
print("The Array is : ", arr)
arr = np.where(arr == max(arr),0,arr)
print("After Changes, The array is : ", arr)

The Array is :  [27 30 74 87 41 71 57 23 86 49]
After Changes, The array is :  [27 30 74  0 41 71 57 23 86 49]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [105]:
#This is the size of the array
size = 10
#This is the datatype of the structured array
datatype = [('x',float),('y',float)]
#Now, I defined an array of the datatype I made in the previous line 
arr= np.zeros(size, dtype=datatype)
#Now, I am filling the structured array
arr['x'] = np.random.rand(size)
arr['y'] = np.random.rand(size)
print("The Structured array is as follows :\n",arr)

The Structured array is as follows :
 [(0.53558397, 0.3445938 ) (0.48102043, 0.39692578)
 (0.14576957, 0.27208227) (0.63551543, 0.28589671)
 (0.25652646, 0.89869892) (0.32143041, 0.86160041)
 (0.94694199, 0.51330487) (0.90481503, 0.9564138 )
 (0.47933782, 0.73256564) (0.79316277, 0.45836153)]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [6]:
import numpy as np
x =  np.random.randint(1,11,10)
y =  np.random.randint(11,21,10)
cauchymatrix = 1/(x-y)
print( f"X : {x}", f"Y: {y}",f"Cauchy Matrix : {cauchymatrix}",sep="\n")

X : [6 8 7 8 4 6 4 5 9 2]
Y: [12 12 11 11 17 12 17 18 17 16]
Cauchy Matrix : [-0.16666667 -0.25       -0.25       -0.33333333 -0.07692308 -0.16666667
 -0.07692308 -0.07692308 -0.125      -0.07142857]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [31]:
 import numpy as np

# Get all scalar types recognized by NumPy, excluding non-numeric types
scalar_types = [np.dtype(t) for t in np.ScalarType if np.dtype(t).kind in ('f', 'i', 'u')]

for dtype in scalar_types:
    info = np.iinfo(dtype) if np.issubdtype(dtype, np.integer) else np.finfo(dtype)
    print(f"{dtype.name}: Min {info.min}, Max: {info.max}")

int32: Min -2147483648, Max: 2147483647
float64: Min -1.7976931348623157e+308, Max: 1.7976931348623157e+308
float16: Min -65504.0, Max: 65504.0
float32: Min -3.4028234663852886e+38, Max: 3.4028234663852886e+38
float64: Min -1.7976931348623157e+308, Max: 1.7976931348623157e+308
float64: Min -1.7976931348623157e+308, Max: 1.7976931348623157e+308
int8: Min -128, Max: 127
int16: Min -32768, Max: 32767
int32: Min -2147483648, Max: 2147483647
int32: Min -2147483648, Max: 2147483647
int64: Min -9223372036854775808, Max: 9223372036854775807
uint8: Min 0, Max: 255
uint16: Min 0, Max: 65535
uint32: Min 0, Max: 4294967295
uint32: Min 0, Max: 4294967295
uint64: Min 0, Max: 18446744073709551615


#### 49. How to print all the values of an array? (★★☆)

In [38]:
import numpy as np
arr = np.random.randint(11,200,10)
for element in arr:
    print(element)

57
171
96
136
184
61
115
165
117
53


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [42]:
scalar = 5.5
vector = np.random.randint(6,16,10)
print(vector)
index = np.abs(vector - scalar).argmin()
print(vector[index])

[11 10 14 15  8  9 11  8 14 15]
8


argmin() returns the index of the minimum value in a numpy array object.<br>
Here, the first line is the scalar value for which the closest value in the vector is to be found.<br>
So, to find we make an array that contains absolute difference between each element and the scalar value.<br>
Then the index of minmum absolute value is obtainted using the argmin function of the numpy module.<br>
Then, this index value is used to print that value inside the print funtion.

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [14]:
import numpy as np
data_type =  [('X', float),('Y', float),('color',[('r',int),('g',int),('b',int)])]
data_points = [{'X':12,'Y':13,'color':(255,0,0)},{'X':16,'Y':19,'color':(0,255,0)},{'X':20,'Y':18,'color':(0,0,255)}]
structured_array=np.empty((0,),dtype = data_type)
for p in data_points:
    structured_array = np.append(structured_array,np.array([(p['X'],p['Y'],p['color'])], dtype = data_type))
print(structured_array)

[(12., 13., (255,   0,   0)) (16., 19., (  0, 255,   0))
 (20., 18., (  0,   0, 255))]


#### 52. Consider a random vector with shape (10,2) representing coordinates, find point by point distances (★★☆)

In [15]:
import numpy as np
Z = np.random.randint(1,21,20).reshape(10,2)
# Here by extracting the first column and the second column,using slicing(z[:,0],z[:,1]) we get a 1D array
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
# Then the above np.atleast_2d() Converts the input into a 2D array
# Then We smartly find distance of one point with that of other by using transpose 
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[ 0.         12.04159458 16.03121954  1.41421356  9.21954446 16.
   8.          7.28010989 10.          9.05538514]
 [12.04159458  0.          4.         13.15294644  8.60232527 20.80865205
  15.         12.80624847 10.81665383  3.60555128]
 [16.03121954  4.          0.         17.11724277 11.40175425 23.34523506
  18.35755975 16.1245155  13.45362405  7.28010989]
 [ 1.41421356 13.15294644 17.11724277  0.          9.43398113 15.03329638
   7.07106781  6.70820393  9.89949494 10.        ]
 [ 9.21954446  8.60232527 11.40175425  9.43398113  0.         12.20655562
   7.28010989  5.09901951  2.23606798  5.38516481]
 [16.         20.80865205 23.34523506 15.03329638 12.20655562  0.
   8.          9.21954446 10.         17.49285568]
 [ 8.         15.         18.35755975  7.07106781  7.28010989  8.
   0.          2.23606798  6.         11.40175425]
 [ 7.28010989 12.80624847 16.1245155   6.70820393  5.09901951  9.21954446
   2.23606798  0.          4.12310563  9.21954446]
 [10.         10.8166538

## Step Wise Calucation to deep dive to understand the logic

In [17]:
X

array([[ 2,  1,  1,  3,  8, 18, 10,  9, 10,  3]])

In [18]:
X.T

array([[ 2],
       [ 1],
       [ 1],
       [ 3],
       [ 8],
       [18],
       [10],
       [ 9],
       [10],
       [ 3]])

In [16]:
X-X.T

array([[  0,  -1,  -1,   1,   6,  16,   8,   7,   8,   1],
       [  1,   0,   0,   2,   7,  17,   9,   8,   9,   2],
       [  1,   0,   0,   2,   7,  17,   9,   8,   9,   2],
       [ -1,  -2,  -2,   0,   5,  15,   7,   6,   7,   0],
       [ -6,  -7,  -7,  -5,   0,  10,   2,   1,   2,  -5],
       [-16, -17, -17, -15, -10,   0,  -8,  -9,  -8, -15],
       [ -8,  -9,  -9,  -7,  -2,   8,   0,  -1,   0,  -7],
       [ -7,  -8,  -8,  -6,  -1,   9,   1,   0,   1,  -6],
       [ -8,  -9,  -9,  -7,  -2,   8,   0,  -1,   0,  -7],
       [ -1,  -2,  -2,   0,   5,  15,   7,   6,   7,   0]])

In [19]:
(X-X.T)**2

array([[  0,   1,   1,   1,  36, 256,  64,  49,  64,   1],
       [  1,   0,   0,   4,  49, 289,  81,  64,  81,   4],
       [  1,   0,   0,   4,  49, 289,  81,  64,  81,   4],
       [  1,   4,   4,   0,  25, 225,  49,  36,  49,   0],
       [ 36,  49,  49,  25,   0, 100,   4,   1,   4,  25],
       [256, 289, 289, 225, 100,   0,  64,  81,  64, 225],
       [ 64,  81,  81,  49,   4,  64,   0,   1,   0,  49],
       [ 49,  64,  64,  36,   1,  81,   1,   0,   1,  36],
       [ 64,  81,  81,  49,   4,  64,   0,   1,   0,  49],
       [  1,   4,   4,   0,  25, 225,  49,  36,  49,   0]])

In [22]:
#Similarly 
(Y-Y.T)**2

array([[  0, 144, 256,   1,  49,   0,   0,   4,  36,  81],
       [144,   0,  16, 169,  25, 144, 144, 100,  36,   9],
       [256,  16,   0, 289,  81, 256, 256, 196, 100,  49],
       [  1, 169, 289,   0,  64,   1,   1,   9,  49, 100],
       [ 49,  25,  81,  64,   0,  49,  49,  25,   1,   4],
       [  0, 144, 256,   1,  49,   0,   0,   4,  36,  81],
       [  0, 144, 256,   1,  49,   0,   0,   4,  36,  81],
       [  4, 100, 196,   9,  25,   4,   4,   0,  16,  49],
       [ 36,  36, 100,  49,   1,  36,  36,  16,   0,   9],
       [ 81,   9,  49, 100,   4,  81,  81,  49,   9,   0]])

In [21]:
np.sqrt((X-X.T)**2 + (Y-Y.T)**2)

array([[ 0.        , 12.04159458, 16.03121954,  1.41421356,  9.21954446,
        16.        ,  8.        ,  7.28010989, 10.        ,  9.05538514],
       [12.04159458,  0.        ,  4.        , 13.15294644,  8.60232527,
        20.80865205, 15.        , 12.80624847, 10.81665383,  3.60555128],
       [16.03121954,  4.        ,  0.        , 17.11724277, 11.40175425,
        23.34523506, 18.35755975, 16.1245155 , 13.45362405,  7.28010989],
       [ 1.41421356, 13.15294644, 17.11724277,  0.        ,  9.43398113,
        15.03329638,  7.07106781,  6.70820393,  9.89949494, 10.        ],
       [ 9.21954446,  8.60232527, 11.40175425,  9.43398113,  0.        ,
        12.20655562,  7.28010989,  5.09901951,  2.23606798,  5.38516481],
       [16.        , 20.80865205, 23.34523506, 15.03329638, 12.20655562,
         0.        ,  8.        ,  9.21954446, 10.        , 17.49285568],
       [ 8.        , 15.        , 18.35755975,  7.07106781,  7.28010989,
         8.        ,  0.        ,  2.23606798

In [5]:
# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.24864981 0.45986087 0.98212011 0.21894281 0.66925033
  0.51970458 0.07135872 0.54837736 0.14240373]
 [0.24864981 0.         0.36817062 0.95243514 0.24511853 0.607314
  0.29503742 0.2165769  0.69615034 0.11041349]
 [0.45986087 0.36817062 0.         0.58649652 0.24705144 0.23932942
  0.29452223 0.4873723  0.53682942 0.41292612]
 [0.98212011 0.95243514 0.58649652 0.         0.77038064 0.34879489
  0.82575359 1.03082298 0.67006095 0.98009604]
 [0.21894281 0.24511853 0.24705144 0.77038064 0.         0.45052643
  0.39354613 0.26066934 0.45456996 0.22126429]
 [0.66925033 0.607314   0.23932942 0.34879489 0.45052643 0.
  0.48724249 0.70826798 0.54136819 0.64498127]
 [0.51970458 0.29503742 0.29452223 0.82575359 0.39354613 0.48724249
  0.         0.50511687 0.80594556 0.39931821]
 [0.07135872 0.2165769  0.4873723  1.03082298 0.26066934 0.70826798
  0.50511687 0.         0.61916104 0.10669493]
 [0.54837736 0.69615034 0.53682942 0.67006095 0.45456996 0.54136819
  0.80594556 0.6191610

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [35]:
import numpy as np
arr = np.array([1,2,3,4,5], dtype = 'int32')
print(arr)
print(arr.dtype)
arr=arr.astype('float32')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32
[1. 2. 3. 4. 5.]
float32


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [1]:
import numpy as np
data = np.genfromtxt('file.txt',delimiter = ',',dtype='float32',filling_values = np.nan)
print(data)
print(type(data))

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]
<class 'numpy.ndarray'>


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [2]:
import numpy as np
data = np.arange(1,7).reshape(2,3)
for index, value in np.ndenumerate(data):
    print(index,value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

Keeping it on halt because I want to finish the maths used for Data Science 

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [17]:
import numpy as np
def place_random_elements(array,p,value):
    flat_array = array.flatten()
    random_indices = np.random.choice(flat_array.size, size = p, replace = False)
    print(random_indices)
    flat_array[random_indices] = value
    return flat_array.reshape(array.shape)

arr = np.zeros(25).reshape(5,5)
updated_array = place_random_elements(arr,5,1)
print(arr)
print(updated_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]
[ 4  6  9 20 12]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [28]:
import numpy as np
arr = np.random.randint(23,45,25).reshape(5,5)
row, column = arr.shape
print(arr)
for i in range(0,row):
    arr[i,:]=arr[i,:]-np.mean(arr[i,:])
print(arr)

[[39 39 32 40 26]
 [24 35 41 44 30]
 [39 40 27 34 43]
 [28 28 39 28 44]
 [25 23 32 38 28]]
[[  3   3  -3   4  -9]
 [-10   0   6   9  -4]
 [  2   3  -9  -2   6]
 [ -5  -5   5  -5  10]
 [ -4  -6   2   8  -1]]


#### 59. How to sort an array by the nth column? (★★☆)

In [35]:
import numpy as np
arr = np.random.randint(23,45,25).reshape(5,5)
n=3
print("Unsorted : \n", arr)
indices =  np.argsort(arr[:,n])
print("Sorted : \n", arr[indices])

Unsorted : 
 [[27 42 33 23 35]
 [23 24 41 40 36]
 [35 26 38 36 24]
 [31 25 34 23 25]
 [35 44 43 38 25]]
Sorted : 
 [[27 42 33 23 35]
 [31 25 34 23 25]
 [35 26 38 36 24]
 [35 44 43 38 25]
 [23 24 41 40 36]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [41]:
#Way 1
import numpy as np
arr = np.array([[1,2,3,np.nan,5],
               [1,2,3,np.nan,5],
               [1,2,3,np.nan,5],
               [1,2,3,np.nan,5],
               [1,2,3,np.nan,5]])
if np.any(np.all(np.isnan(arr), axis =0)):
    print("Yes!! At least one column is null")
else:
    print("No column is null")

Yes!! At least one column is null


In [38]:
#Way 2
import numpy as np
arr = np.array([[1,2,3,np.nan,5],
               [1,2,3,np.nan,5],
               [1,2,3,np.nan,5],
               [1,2,3,np.nan,5],
               [1,2,3,np.nan,5]])
Flag=False
row, column = arr.shape
print(arr)
for i in range(0,column):
    if np.all(np.isnan(arr[:,i])):
        Flag = True
        break
if Flag == True:
    print("Yes!! It has ")
else:
    print("NO!!It doesn't have")

[[ 1.  2.  3. nan  5.]
 [ 1.  2.  3. nan  5.]
 [ 1.  2.  3. nan  5.]
 [ 1.  2.  3. nan  5.]
 [ 1.  2.  3. nan  5.]]
Yes!! It has 


#### 61. Find the nearest value from a given value in an array (★★☆)

In [9]:
import numpy as np
given_value = int(input("Enter a number : "))
array =  np.random.randint(1,101,50)
print(array)
index = np.abs(array - given_value).argmin()
print("The value you have entered : ", given_value)
print("The nearest Value in array : ",array[index])

Enter a number : 85
[  9  91  12  23  60  67  78  78  43   6  28  52  74  19  28  97  81  15
  89  21  76  95  26  63  83  47  35  98  94   5  51  54  26  93   8  74
  53  69   4  26  75  71 100  73  34  39  68  60  11  35]
The value you have entered :  85
The nearest Value in array :  83


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [31]:
#Creating a user defined iterator 
import numpy as np

def sum_iterator(a,b):
    ans = np.zeros((3,3))
    for i in range(3):
        for j in range(3):
            ans[i,j] = next(a) + next (b)
    return ans

arr1 = iter(np.array([1,2,3]))
arr2 = iter(np.array([[1],[2],[3]])) 
result=sum_iterator(arr1,arr2)

StopIteration: 

In [3]:
def sum_iterator(a,b):
    ans = next(a) + next(b)
    return ans
import numpy as np
arr1 = iter(np.array([1,2,3]))
arr2 = iter(np.array([[1],[2],[3]])) 

In [4]:
sum_iterator(arr1,arr2)

array([2])

In [5]:
sum_iterator(arr1,arr2)

array([4])

In [6]:
sum_iterator(arr1,arr2)

array([6])

#### 63. Create an array class that has a name attribute (★★☆)

In [12]:
import numpy as np
class named_array(np.ndarray):    
    def __new__(cls,arr,name = None):
        obj = np.asarray(arr).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self,obj):
        if obj is None:
            return 
        self.name = getattr(obj, 'name' , None)
array = named_array([12,34,56], name = 'weightage')
print(array)
print(array.name)

[12 34 56]
weightage


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [22]:
import numpy as np
vector =  np.random.randint(1,11,10)
indices = np.random.randint(0,10,10)
print("Vector before adding 1 indexed by a second vector : ", vector)
print("Indices to be updated are :  ", indices)
unique_indices, count = np.unique(indices, return_counts= True)
vector[unique_indices]+=1*count
print("Vector after adding 1 indexed by a second vector : ", vector)

Vector before adding 1 indexed by a second vector :  [3 7 4 1 9 2 3 4 4 1]
Indices to be updated are :   [0 9 8 2 1 4 8 1 1 7]
Vector after adding 1 indexed by a second vector :  [ 4 10  5  1 10  2  3  5  6  2]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [28]:
X =  np.random.randint(1,11,10)
I =  [2,3,4,5]
F = np.zeros(len(I))
F= [X[i] for i in I]
F

[4, 9, 8, 7]

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [3]:
import numpy as np
def unique_color(image):
    reshaped_image = image.reshape((-1,3))
    colors_list = [tuple(row) for row in reshaped_image]
    unique = len(np.unique(colors_list,axis=0))
    return unique
    
image = np.array([
    [[255, 0, 0], [0, 255, 0], [0, 0, 255], [255, 255, 255]],
    [[255, 0, 0], [0, 255, 0], [0, 0, 255], [255, 255, 255]],
    [[255, 0, 0], [0, 255, 0], [0, 0, 255], [255, 255, 255]],
    [[255, 0, 0], [0, 255, 0], [0, 0, 255], [255, 255, 255]]
], dtype=np.uint8)

print("The number of unique colors : ", unique_color(image))

The number of unique colors :  4


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [4]:
import numpy as np
array  = np.random.randint(0,10, size = (2,3,4,2))
result = np.sum(array, axis=(-2,-1))
print("The array is :\n", array)
print("The sum along last two axis is: ", result)

The array is :
 [[[[3 0]
   [9 0]
   [1 7]
   [7 3]]

  [[2 8]
   [5 2]
   [2 8]
   [1 3]]

  [[2 3]
   [6 2]
   [0 3]
   [0 1]]]


 [[[9 1]
   [7 7]
   [3 4]
   [6 7]]

  [[7 3]
   [9 5]
   [1 4]
   [4 0]]

  [[5 2]
   [7 3]
   [4 9]
   [6 3]]]]
The sum along last two axis is:  [[30 31 17]
 [44 33 39]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [11]:
import numpy as np
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sum = np.bincount(S, weights = D)
D_count = np.bincount(S)
print(D_sum/D_count)

[0.46843211 0.38109851 0.40639272 0.42251463 0.51262291 0.5974578
 0.62655247 0.58051505 0.52660445 0.39109076]


#### 69. How to get the diagonal of a dot product? (★★★)

In [21]:
import numpy as np
a = np.arange(1,10).reshape(3,3)
b = np.arange(11,20).reshape(3,3)
print(a,"\n",b)
#Way 1
print(np.diag(np.dot(a,b)))
#Way 2
print(np.sum(a*b.T, axis = 1))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
[ 90 231 390]
[ 90 231 390]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [30]:
import numpy as np 
arr =  np.array([1,2,3,4,5])
zeros = np.zeros(3,dtype=type(arr))
ans = np.zeros(len(arr)+(len(arr)-1)*3,dtype=type(arr))
ans[::4] = arr
print(ans)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [36]:
import numpy as np
arr1=np.random.randint(0,50,75).reshape(5,5,3)
arr2=np.random.randint(0,50,25).reshape(5,5)
arr2=np.atleast_3d(arr2)
print(arr1,arr2,sep="\n")
product=arr1*arr2
print(product)

[[[49 26 21]
  [23 13 40]
  [19 10 43]
  [ 0 26 34]
  [30 38 32]]

 [[30 44 16]
  [18  6 35]
  [26 19 33]
  [39 21 17]
  [12 19 20]]

 [[18 43 41]
  [28 29 22]
  [23 29  4]
  [36 26 45]
  [11  4 21]]

 [[29 12 29]
  [21 34 10]
  [ 0 15 32]
  [25 14 39]
  [18 28 35]]

 [[44 28 45]
  [32 38 24]
  [19  2 29]
  [25 40 18]
  [42 33 13]]]
[[[ 9]
  [26]
  [33]
  [14]
  [14]]

 [[21]
  [28]
  [48]
  [14]
  [45]]

 [[23]
  [27]
  [37]
  [48]
  [12]]

 [[33]
  [20]
  [ 9]
  [41]
  [39]]

 [[37]
  [ 3]
  [38]
  [22]
  [ 5]]]
[[[ 441  234  189]
  [ 598  338 1040]
  [ 627  330 1419]
  [   0  364  476]
  [ 420  532  448]]

 [[ 630  924  336]
  [ 504  168  980]
  [1248  912 1584]
  [ 546  294  238]
  [ 540  855  900]]

 [[ 414  989  943]
  [ 756  783  594]
  [ 851 1073  148]
  [1728 1248 2160]
  [ 132   48  252]]

 [[ 957  396  957]
  [ 420  680  200]
  [   0  135  288]
  [1025  574 1599]
  [ 702 1092 1365]]

 [[1628 1036 1665]
  [  96  114   72]
  [ 722   76 1102]
  [ 550  880  396]
  [ 210  165   6

#### 72. How to swap two rows of an array? (★★★)

In [42]:
arr2=np.random.randint(0,50,25).reshape(5,5)
print(arr2)
arr2[[0,1]]=arr2[[1,0]]
print(arr2)

[[22 27 30 48 12]
 [20 31  6  8 35]
 [31 30 36  9 16]
 [36 17 10 12  4]
 [49 36 49 26 36]]
[[20 31  6  8 35]
 [22 27 30 48 12]
 [31 30 36  9 16]
 [36 17 10 12  4]
 [49 36 49 26 36]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

cont. after discussion m

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)