# 100 numpy excellent problems
Source: https://github.com/rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.24.3'

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
arr.size


10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
np.add?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
arr=np.arange(10,49)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
arr[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.randint(0,27,size=(3,3,3))

array([[[25, 14, 20],
        [ 3, 10, 15],
        [11,  8, 12]],

       [[23, 14, 10],
        [25, 12, 19],
        [21, 17,  2]],

       [[18, 10,  6],
        [ 0, 20, 10],
        [13, 13, 10]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
arr1=np.random.randint(1200,1299,size=(10,10))
print(arr1.min())
print(arr1.max())

1201
1298


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
arr2 = np.random.randint(23,56,size=(30))
format(arr2.mean(),".2f")

'38.70'

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
arr3=np.ones(25).reshape(5,5)
arr3[1:-1,1:-1]=0
print(arr3)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
arr1=np.random.randint(1200,1299,size=(10,10))
arr1[:1,:]=arr1[:,:1]=arr1[:,len(arr1)-1:]=arr1[len(arr1)-1:,:]=0
arr1

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0, 1280, 1259, 1214, 1210, 1265, 1276, 1281, 1221,    0],
       [   0, 1272, 1202, 1273, 1258, 1215, 1278, 1277, 1226,    0],
       [   0, 1221, 1215, 1257, 1298, 1231, 1262, 1294, 1248,    0],
       [   0, 1298, 1224, 1237, 1285, 1206, 1247, 1209, 1278,    0],
       [   0, 1215, 1288, 1238, 1210, 1255, 1222, 1268, 1290,    0],
       [   0, 1223, 1222, 1288, 1244, 1201, 1224, 1205, 1249,    0],
       [   0, 1233, 1243, 1276, 1205, 1256, 1238, 1234, 1248,    0],
       [   0, 1287, 1242, 1237, 1234, 1288, 1282, 1268, 1285,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
#Beginner approach
arr3=np.zeros(25).reshape(5,5)
for i,j in zip(range(0,len(arr3)),range(1,len(arr3))):
    arr3[j][i]=j
print(arr3)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [20]:
#Numpy approach 
arr= np.zeros((5,5))
np.fill_diagonal(arr[1:],[1,2,3,4])
print(arr)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [21]:
arr= np.zeros((8,8))
arr[::2,::2]=1
arr[1::2, 1::2] = 1 
print(arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [22]:
#My answer after watching fourth part of matrix
arr=np.array([[list(range(0,8))]*7]*6)
arr[1][5][3]=100
print(arr)

[[[  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]]

 [[  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2 100   4   5   6   7]
  [  0   1   2   3   4   5   6   7]]

 [[  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]]

 [[  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4   5   6   7]
  [  0   1   2   3   4

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [27]:
arr=np.array([[1,0],[0,1]])
check_board=np.tile(arr,(4,4))
check_board

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [16]:
import numpy as np 
import matplotlib.pyplot as plt
orginal_matrix = np.random.rand(5,5)
mean = np.mean(orginal_matrix)
std_dev = np.std(orginal_matrix)
normalized_matrix = (orginal_matrix - mean)/ std_dev
print(" Orginal Matrix\n ",  orginal_matrix)
print(" Normalized Matrix\n ",  normalized_matrix)

 Orginal Matrix
  [[0.13992156 0.51970335 0.30238302 0.10855903 0.04627473]
 [0.17956199 0.29669616 0.62959021 0.16254368 0.07857205]
 [0.71052995 0.44463907 0.11814946 0.7329878  0.05761887]
 [0.70279655 0.45704813 0.31235217 0.96990882 0.57358658]
 [0.808817   0.76621215 0.32035292 0.22154408 0.84675482]]
 Normalized Matrix
  [[-0.9998956   0.35457227 -0.42048701 -1.11174811 -1.33388116]
 [-0.8585205  -0.44076886  0.74647686 -0.91921526 -1.21869479]
 [ 1.03514333  0.08686022 -1.07754444  1.11523786 -1.29342299]
 [ 1.00756267  0.13111636 -0.38493268  1.96020179  0.54674344]
 [ 1.38567792  1.23373042 -0.3563985  -0.70879403  1.5209808 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [29]:
import numpy as np
rgba = np.dtype([('r', np.uint32),('g', np.uint32),('b', np.uint32),('a', np.uint32)])
value = np.array([(250, 0, 0, 255),
                  (0, 255, 0, 255),
                  (0, 0, 255, 255),
                  (255, 255, 255, 255)], dtype =rgba)
print(value)

[(250,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)
 (255, 255, 255, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [31]:
import numpy as np
arr1 = np.random.rand(5,3)
arr2 = np.random.rand(3,2)
print(arr1)
print(arr2)
arr1@arr2

[[0.74003165 0.54958208 0.45504712]
 [0.72578545 0.52546562 0.28527561]
 [0.47160572 0.9953643  0.22950678]
 [0.2165867  0.63534404 0.96645403]
 [0.61107722 0.93583567 0.39700595]]
[[0.62524871 0.03874115]
 [0.19014238 0.14296761]
 [0.31316516 0.71419194]]


array([[0.70970758, 0.4322331 ],
       [0.64304808, 0.30698386],
       [0.55600533, 0.32448729],
       [0.55888612, 0.78945812],
       [0.6843457 , 0.44100647]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [43]:
arr = np.random.randint(4,12,25)
arr = np.where( (3<arr) & (arr<8), -arr, arr)
print(arr)

[-4 -6  9  9 -4 -4 11 -4  8 -5 11 -5 -4  9  9 11 10 10 -6 11 10 11 -7  8
 -5]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [45]:
'''This is the sum() function of the core python. 
Thus, the second argument represents the initial value of the sum 
function. Hence, sum=-1+0+1+2+3+4 = 9 '''
print(sum(range(5),-1))
from numpy import *
'''After importing numpy, we are usign sum() used which is there in
numpy. And the second argument represent the axis i.e. sum along 
axis 1'''
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [30]:
import numpy as np
z=np.arange(5)
print(" z : ", z)
#Expression 1:it does N^N where N is an element of the vector z
print("Result of expression 1: ", z**z)
#Expression 2: Expression is evaluated on bitwise operator and from left to right.
print("Result of expression 2: ",2 << z >> 2)
#Exoression 3: 
print("Result of expression 3: ", z<-z)
#Expression 4: converts all elment into a complex number
print("Result of expression 4: ", 1j*z)
#Expression 5: 
print("Result of expression 5: ",z/1/1)
#Expression 6: This is an ambiguous expression and results in an error
print("Result of expression 5: ",z<z<z)

 z :  [0 1 2 3 4]
Result of expression 1:  [  1   1   4  27 256]
Result of expression 2:  [0 1 2 4 8]
Result of expression 3:  [False False False False False]
Result of expression 4:  [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
Result of expression 5:  [0. 1. 2. 3. 4.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [32]:
np.array(0) / np.array(0)       #Divide By Zero (Runtime Error)
np.array(0) // np.array(0)      #Divide By Zero (Runtime Error)
'''Convert nan into minimum integer value that the data type can represent and then back to float(whihc results in a 
a negative value)'''
np.array([np.nan]).astype(int).astype(float) 

C:\Users\user\AppData\Local\Temp\ipykernel_5700\4124992270.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)       #Divide By Zero (Runtime Error)
C:\Users\user\AppData\Local\Temp\ipykernel_5700\4124992270.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)      #Divide By Zero (Runtime Error)
C:\Users\user\AppData\Local\Temp\ipykernel_5700\4124992270.py:5: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [51]:
import numpy as np
arr =  np.random.randn(10)
print(arr)
rounded_arr = np.ceil(arr[arr>=0])
rounded_arr1 = np.floor(arr[arr < 0])
final =  np.concatenate([rounded_arr,rounded_arr1])
print(final)

[-1.74641099 -1.3656557  -0.44242372  0.34476221 -0.05118213  0.66537005
 -0.61676653 -1.06245415 -0.42980825  0.87076257]
[ 1.  1.  1. -2. -2. -1. -1. -1. -2. -1.]










#### 30. How to find common values between two arrays? (★☆☆)

In [70]:
arr1 = np.random.randint(12,20,25)
arr2 = np.random.randint(12,20,25)
arr3 = arr1[np.isin(arr1, arr2)]
print("Array1 : ", arr1, "Array 2: ", arr2,sep="\n")
print("Common Element between the two arrays : ",arr3)

Array1 : 
[12 19 17 13 14 13 13 15 12 16 18 19 16 19 12 12 17 18 16 13 12 19 17 13
 14]
Array 2: 
[12 14 15 18 16 15 16 19 18 15 19 16 18 12 19 12 15 15 14 15 17 12 13 16
 13]
Common Element between the two arrays :  [12 19 17 13 14 13 13 15 12 16 18 19 16 19 12 12 17 18 16 13 12 19 17 13
 14]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [72]:
import numpy as np 
np.seterr(all='ignore')

#Reset it 
np.seterr(all=None)

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [74]:
bool(np.sqrt(-1 == np.emath.sqrt(-1)))

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [85]:
import numpy as np
today =  np.datetime64('today','D')
yd = today - np.timedelta64(1,'D')
tm = today + np.timedelta64(1,'D')
print("Yesterday's Date :", yd)
print(" Today's Date : ", today)
print("Tomorrow's Date : ", tm)

Yesterday's Date : 2024-02-17
 Today's Date :  2024-02-18
Tomorrow's Date :  2024-02-19


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [9]:
import numpy as np
import datetime

year = eval(input("Enter the year : "))
month = eval(input("Enter the month (in integer format) : "))

if 0 < month < 13:
    start_date = datetime.date(year, month, 1)
    num_days = (start_date.replace(month=start_date.month % 12 + 1, day=1) - start_date).days
    dates = [start_date + datetime.timedelta(days=i) for i in range(num_days)]

    for date in dates:
        print(date)
else:
    print("There is no such month in a year")

Enter the year : 2024
Enter the month (in integer format) : 2
2024-02-01
2024-02-02
2024-02-03
2024-02-04
2024-02-05
2024-02-06
2024-02-07
2024-02-08
2024-02-09
2024-02-10
2024-02-11
2024-02-12
2024-02-13
2024-02-14
2024-02-15
2024-02-16
2024-02-17
2024-02-18
2024-02-19
2024-02-20
2024-02-21
2024-02-22
2024-02-23
2024-02-24
2024-02-25
2024-02-26
2024-02-27
2024-02-28
2024-02-29


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

Save and commit your work.

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)