# Numpy: Introduction

• It is a python package and stands for Numerical Python. It is consist of multidimentional array obeject and routines for processing of array.\
•It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it.\
• It is a fundamental package for scintific computing in python, and provides following funtionalities\
    ► NumPy can be used to perform a wide variety of mathematical operations on arrays.\
    ► It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices\
    ► Have linear algebra, Fourier Tranform, and random number Capabilities\
    ► it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.\
•The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.


## &emsp;Why Numpy?

► To perform Mathematical and Logical operations on arrya\
► It provides efficient storage and manipulation of numerical arrays which is needed in Data Science\
► Numpy array form the core of nearly entire ecosystem of data science tools in python


## &emsp; Importing Numpy and Checking Version

In [1]:
#Method 1
import numpy 
numpy.__version__

'1.24.3'

In [2]:
#Method 2
!pip show numpy 

Name: numpy
Version: 1.24.3
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD-3-Clause
Location: C:\Users\user\anaconda3\Lib\site-packages
Requires: 
Required-by: astropy, bokeh, Bottleneck, contourpy, daal4py, datashader, datashape, gensim, h5py, holoviews, hvplot, imagecodecs, imageio, imbalanced-learn, matplotlib, mkl-fft, mkl-random, numba, numexpr, pandas, patsy, pyarrow, pyerfa, PyWavelets, scikit-image, scikit-learn, scipy, seaborn, statsmodels, tables, tifffile, transformers, xarray


##### &nbsp;&nbsp;We can give an alias to numpy using operator "as"

In [3]:
import numpy as np
np.__version__

'1.24.3'

#### » If numpy is not intalled in your anaconda, simply Run Below Command

In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


If it is alreafdy installed above command will show following result

In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


 <b>Note:</b> pip is the command used to install any library in python. pip stands for python index package

## What’s the difference between a Python list and a NumPy array?
There are several important differences between NumPy arrays and the standard Python sequences:

► NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.<br>

► The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.<br>

► NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.<br>

► A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.<br>

### Why use NumPy?

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

## What is an array?

An array is usually a fixed-size container of items of the same type and size. The number of dimensions and items in an array is defined by its shape. The shape of an array is a tuple of non-negative integers that specify the sizes of each dimension.

In NumPy, dimensions are called axes. This means that if you have a 2D array that looks like this:

[[0., 0., 0.],<br>
 [1., 1., 1.]]<br><br>
Your array has 2 axes. The first axis has a length of 2 and the second axis has a length of 3.



## Rank and Shape of an Array
The rank of the array is the number of dimensions. The shape of the array is a tuple of integers giving the size of the array along each dimension.

## ndarray
The NumPy ndarray class is used to represent both matrices and vectors. A vector is an array with a single dimension (there’s no difference between row and column vectors), while a matrix refers to an array with two dimensions. For 3-D or higher dimensional arrays, the term tensor is also commonly used.

## &emsp; Bounding Numpy Package local Variable

The numpy package is bound to the local numpy variable. The Syntax <b>import _____ as ____ </b> allows us to bind the import to the local variable. This local varible can have name of your choice. We do so usually to avoid name collision.

## How to create a basic array

In [10]:
#Example 
import numpy as np
a=(1,2,3,4,5)
b=np.array(a)
print(b)

[1 2 3 4 5]


The above code converts the tuple 'a' in an array 'b'.

In [11]:
#More Example 
import numpy as np
a=np.array((1,2,3))

<img src="https://github.com/SimmiSheetalJain/Medias_for_notes_and_blogs/blob/main/array_visualization.png?raw=true">

In [12]:
#Let's see type of a
type(a)

numpy.ndarray

#### Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s or 1's. Or even an empty array! The function empty creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed 

In [13]:
#Example
import numpy as np
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
#Example
import numpy as np
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
#Example
import numpy as np
np.empty(5)

array([1., 1., 1., 1., 1.])

In [217]:
#example
np.full([2,3],42)

array([[42, 42, 42],
       [42, 42, 42]])

#### You can create an array with a range of elements:

In [16]:
#Example
import numpy as np
np.arange(5)

array([0, 1, 2, 3, 4])

#### An array that contains a range of evenly spaced intervals is crated by specifying the first number, last number, and the step size.

In [17]:
#Example
import numpy as np
np.arange(2,13,2)

array([ 2,  4,  6,  8, 10, 12])

### You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:

In [18]:
np.linspace(10,21,num=5)

array([10.  , 12.75, 15.5 , 18.25, 21.  ])

#### Creating array with diagonal element as 1

In [19]:
#Example 1
arr=np.eye((3))
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
#example 2
arr=np.eye(3,5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


### Making an array storing user's entered value

In [22]:
l=[]
for i in range(1,5):
    ele=int(input(f"Enter value {i}: "))
    l.append(ele)
print(np.array(l))

Enter value 1: 5
Enter value 2: 4
Enter value 3: 2
Enter value 4: 2
[5 4 2 2]


###### &emsp; &emsp;⦿ Important Points :

###### ♦ We have list in python to serve the purpose of array but list takes much more processing time as compare to array. NumPy intends to provide an array object which is 50x faster than python list. And arrays are faster than list because arrays densely packed in memory due to its homogeneous type and it also frees memory space faster.

###### ♦ Arrays are used in data science whenever speed and resources are essential to be optimized.

###### ♦ NumPy has been written in C++

###### ♦ Dimensions are named as axes in NumPy. Number of Axes are called Rank.

###### ♦The array class of NumPy is known as ndarray. It's oftenly used as alias 'array'

### ■ Few Important Commands on Array

In [23]:
import numpy as np
a=(1,2,3,4,5)
b=np.array(a)
print(b)
#ndim: to produce dimention of an array
print(b.ndim)
#shape:To find shape of array in form of rows and column
print(b.shape)
#size :To print the size of an array
print(b.size)
#dtype : To know the data type of an array
print(b.dtype)

[1 2 3 4 5]
1
(5,)
5
int32


In [24]:
#Another Example:
import numpy as np
arr = np.array([[2,3,4,],[5,6,7]])
print("Array elements : \n",arr)
print("Array Shape is : ",arr.shape)
print("Array size is : ",arr.size)
print("Array data type is : ",arr.dtype)
print("Array dimension is : ",arr.ndim)
print("Array is a type of : ",type(arr))


Array elements : 
 [[2 3 4]
 [5 6 7]]
Array Shape is :  (2, 3)
Array size is :  6
Array data type is :  int32
Array dimension is :  2
Array is a type of :  <class 'numpy.ndarray'>


### &emsp; &emsp;⦿ Speed Comparision of numpy and core python⦿

In [25]:
import time as t
import numpy as n
size=100000
def pure_python_time():
    initiation = t.time() ##time at which code execution started
    list1=range(size)
    list2=range(size)
    sumlist=[list1[i]+list2[i] for i in range(size)]
    return t.time()-initiation #differecnt of initial and ending time of execution

def numpy_time():
    initiation =t.time() ##time at which code execution started
    array1=n.arange(size)
    array2=n.arange(size)
    array_sum =[array1[i]+array2[i] for i in range(size)]
    return t.time()-initiation

print("Time taken by core python  : ", pure_python_time())
print("Time taken by numpy  : ", numpy_time())

Time taken by core python  :  0.05597066879272461
Time taken by numpy  :  0.07495379447937012


In [26]:
#Example
import time as t
import numpy as n
def list_t():
    ini=t.time()
    sum=0
    for i in range(1,15000000):
        sum+=i
    return sum,(t.time()-ini)
def numpy_t():
    ini1=t.time()
    arr=n.random.randint(1,1500000,14)
    sum=0
    for i in arr:
        sum+=i
    return sum,(t.time()-ini1)
a,b=list_t()
x,y=numpy_t()
print(f"List result:\n Sum:{a}, time:{b}")
print(f"Numpy result:\n Sum:{x}, time:{y}")

List result:
 Sum:112499992500000, time:2.1108126640319824
Numpy result:
 Sum:11362576, time:0.006340503692626953


### Difference between Numpy array and list in python

1. Data types storage: <br>
    ✦ In list, we can store different data types.<br>
    ✦ In numpy, we have to choose a particular data type to work with array. Though, we can combine string and number but when go higher we have to deal with one data type <br>
2. Import module <br>
    ✦ For using list data type, we don't have to import any module<br>
    ✦ For numpy array, we need to import numpy  module<br>
3. Numerical Operation<br>
    ✦List is Capable to perform operation but slower that numpy array. <br>
    ✦numpy array works as matrices
4. Modification Capabilities <br>
    ✦List had more modification flexiblities than that of numpy array<br>
5. Memory<br>
    ✦List uses more memory than numpy array<br>
6. speed: list < numpy array

➊ We have already seen how we can create a basic array in "How to create a basic array" section

➋ We can pass value of dimention to 'ndmin'. For example:

In [27]:
arr1=np.array([1,2,3,4],ndmin=2)

In [28]:
#Checking the dimention of the array object 'arr2'
arr1.ndim

2

➌ We can also pass data type specifically while creating an array object. For Example:

In [29]:
arr3=np.array([[1,3,4,],[7,8,9]],dtype=complex)
print(arr3.dtype)
print(arr3)

complex128
[[1.+0.j 3.+0.j 4.+0.j]
 [7.+0.j 8.+0.j 9.+0.j]]


<b>Note:</b> Complex number in python are represented as a+bj, where a, b are real numbers and j is an imaginary number.

➍ len() when applied on an array object, returns the number of rows while size() returns total number of elements.

In [30]:
#Example
arr3=np.array([[1,3,4,],[7,8,9]],dtype=complex)
print(len(arr3))
print(arr3.size)

2
6


### Question: WAP to count the frequency of unique values in NumPy array?

In [32]:
import numpy as np

def count_frequency(arr):
    number, occurrence=np.unique(arr, return_counts=True)
    answer = dict(zip(number, occurrence))
    return answer

n=int(input("How many elements do you have in your array? : "))
arr=[0]*n
for i in range(n):
    element=int(input(f"Enter element number {i+1} : "))
    arr[i]=element
occurrence_Dict=count_frequency(arr)
print(occurrence_Dict)

How many elements do you have in your array? : 5
Enter element number 1 : 45
Enter element number 2 : 24
Enter element number 3 : 15
Enter element number 4 : 85
Enter element number 5 : 45
{15: 1, 24: 1, 45: 2, 85: 1}


<b>Note:</b> unique() function is used to find the unique elements of an array.
### Syntax: 
numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)\

》_return_index_ (optional, default is False): If True, also return the indices of the unique elements.\
》_return_counts_ (optional, default is False): If True, return the count of each unique element.\
》_return_inverse_: If True, also return an array of indices such that if the result is called unique_elements, then ar = unique_elements[unique_inverse]. Or we can also say it returns an array that can be used to reconstruct the original input array.


In [33]:
#Example
import numpy as np

arr = np.array([1, 2, 2, 3, 4, 4, 5])

unique_elements, unique_inverse = np.unique(arr, return_inverse=True)

print("Unique Elements:", unique_elements)
print("Original Array:", unique_elements[unique_inverse])


Unique Elements: [1 2 3 4 5]
Original Array: [1 2 2 3 4 4 5]


》_axis_ (optional, default is None): The axis or axes along which to perform the unique operation. By default, it operates on the flattened input array.

## Create numpy array with random values. 
We use module "random" of numpy array to generate random value array

### ✦ rand(): 
the function is used to generate numbers between 0 and 1

In [34]:
#Example 
var=np.random.rand(5)
print(var)

[0.98300486 0.47335932 0.56072315 0.78267522 0.3296    ]


In [35]:
#Example 
var=np.random.rand(3,2)
print(var)

[[0.35380488 0.00577875]
 [0.90689963 0.7491667 ]
 [0.59775551 0.46564368]]


### ✦ randn():
the function is used to generate a random value close to zero. This may return a positive or negative numbers as well

In [36]:
#Example 
var=np.random.randn(3,2)
print(var)

[[-1.17055973  1.45919558]
 [-0.72777304 -1.39424215]
 [-0.68252691 -0.81290818]]


### ✦ randf():
the funnction for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half-open interval[0.0,1.0)

In [37]:
#Example 
var=np.random.ranf((2,2))
print(var)

[[0.04779336 0.25630227]
 [0.32748573 0.93193255]]


In [38]:
#Example 
var=np.random.ranf((3))
print(var)

[0.53305333 0.1386453  0.4999417 ]


## randint()
the function is used to generate a random number between a given range:\
&emsp;&emsp;Prototype randint(min, max, total_values)

In [39]:
var=np.random.randint(4,20,6)
print(var)

[ 6 17 18 11 18 17]


## Data Types in NumPy Arrays

1. int8, int16, int32, int64: Signed integer types with different bit depths.
2. uint8, uint16, uint32, uint64: Unsigned integer types with different bit depths.
3. float16, float32, float64: Floating-point types with different precision.
4. complex64, complex128: Complex number types with different precision.
5. bool: Boolean type for storing True or False values.

In [40]:
#Example
arr_int32=np.array([1,2,4,4,5,6],dtype=np.int32)
print(arr_int32)
print(arr_int32.dtype)

[1 2 4 4 5 6]
int32


## Shape & Reshaping in Numpy Array

#### shape attribute of an array

In [41]:
#Example: creating a multi dimentional array to reshape
arr=np.array([[[[[[2,2,3,4],[3,4,5,6]]]]]])
print(arr.shape)

(1, 1, 1, 1, 2, 4)


### Reshape 

#### Syntax of reshape():
&emsp;&emsp; numpy.reshape(a, newshape, order='C')

⇨ _a_ is the array to be sorted\
⇨ _newshape_ specifies the new shape of the array. It should be compatible with the original shape.\
⇨ _order_ (optional, default is 'C'): The order in which the elements should be read. It can be 'C' for row-major (default) or 'F' for column-major.

In [42]:
#Example, reshaping above array
arr=np.linspace(3,40,6)
print(arr,"\n")
reshaped_arr=np.reshape(arr,(2,3))
print("Reshaped Array\n: ",reshaped_arr)

[ 3.  10.4 17.8 25.2 32.6 40. ] 

Reshaped Array
:  [[ 3.  10.4 17.8]
 [25.2 32.6 40. ]]


⇨ You can also use the -1 in the newshape argument, and NumPy will automatically calculate the size for that dimension based on the size of the original array. 

In [43]:
#example
import numpy as np
arr=np.array((1,2,3,4,5,6))
re_arr=np.reshape(arr,(2,-1))
print("Original Array\n", arr)
print("Reshaped Array\n", re_arr)

Original Array
 [1 2 3 4 5 6]
Reshaped Array
 [[1 2 3]
 [4 5 6]]


In [44]:
#Example
import numpy as np
arr=np.random.randint(2,11,9)
arr=arr.reshape(3,3)
print(arr)

[[ 2  4  5]
 [ 5  2 10]
 [ 4 10  6]]


## Adding and removing element from an array 

### Adding Elements:

1. Append Elements:
Use numpy.append() to add elements at the end of an array.

In [45]:
#example 
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)
new_element = 6
arr=np.append(arr,new_element)
print(arr)

[1 2 3 4 5]
[1 2 3 4 5 6]


2. Insert Elements:Use numpy.insert() to insert emlements at a specific index in an array.<br>
#### Syntax:  
numpy.insert(arr, obj, values, axis=None)

In [46]:
# Example
print(arr)
arr = np.insert(arr,3,7)
print(arr)

[1 2 3 4 5 6]
[1 2 3 7 4 5 6]


In [47]:
#example 
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)
arr=np.insert(arr,[1,2,3],[40,50,60])
print(arr)

[1 2 3 4 5]
[ 1 40  2 50  3 60  4  5]


### Removing Elements:

1. Remove Elements by Index:Use numpy.delete() to remove elements at a specific index.<br>
#### Syntax:
&emsp;&emsp; arr = np.delete(arr, index)

In [48]:
#Example
print(arr)
arr=np.delete(arr,3)
print(arr)

[ 1 40  2 50  3 60  4  5]
[ 1 40  2  3 60  4  5]


2. Remove element by value: Use boolean indexing to remove elements based on their values.<br>
#### Syntax: 
&emsp;&emsp; arr = arr[arr != value_to_remove]

In [49]:
#Example
import numpy as np
arr=np.arange(2,11)
print(arr)
#removing an element 
arr=arr[arr%2!=0]
print(arr)

[ 2  3  4  5  6  7  8  9 10]
[3 5 7 9]


##### Till here, we have learnt what is multidimensional array object and How to creat an ndarray in different ways.

## Arithmetic with numpy array

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result. ( all the green headings are subtopics of this topic)

In [177]:
#Example
import numpy as np
a=np.arange(1,6)
b=np.arange(6,11)
print(f"Array 1 : {a}, Array 2 : {b}")
#Addition
print(f"Array 1 + Array 2  = {a+b}")
#Subtraction
print(f"Array 1 - Array 2  = {a-b}")
#Multiplication
print(f"Array 1 + Array 2  = {a*b}")
#Divide
print(f"Array 2 ÷ Array 1  = {b//a}")
#Expoinent
print(f"Array 1 ÷ Array 2  = {a**b}")
#Relational Operator
print(f"Array 1 > Array 2  = {a<b}")
#Mathematical Functions
a=np.array([30,45,60,90,120])
res=np.sin(a)
print(f"sine values:  {np.round(res,2)}")  #round function is used for rounding off array elements

Array 1 : [1 2 3 4 5], Array 2 : [ 6  7  8  9 10]
Array 1 + Array 2  = [ 7  9 11 13 15]
Array 1 - Array 2  = [-5 -5 -5 -5 -5]
Array 1 + Array 2  = [ 6 14 24 36 50]
Array 2 ÷ Array 1  = [6 3 2 2 2]
Array 1 ÷ Array 2  = [      1     128    6561  262144 9765625]
Array 1 > Array 2  = [ True  True  True  True  True]
sine values:  [-0.99  0.85 -0.3   0.89  0.58]


####  Let's do some more operation

In [184]:
#example 
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [11,12,13,14]])
arr3 = np.array([[11,12,13,14],
                 [15,16,17,18],
                 [19,20,21,22]])
print(arr2+arr3)

[[12 14 16 18]
 [20 22 24 26]
 [30 32 34 36]]


In [186]:
#example
arr3-arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [ 8,  8,  8,  8]])

<h3 style="color:green;"> Elementwise Product and Matrices Product </h3>

Even in the case of a 2D or n-dimentional array, elements are multiplied elementwise when we use '*' operator 

In [51]:
#Example
arr1=np.arange(2,11)
arr1=np.reshape(arr1,(3,3))
arr2=np.arange(1,10)
arr2=np.reshape(arr2,(3,3))
print(arr1,arr2,arr1*arr2,sep="\n")

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  6 12]
 [20 30 42]
 [56 72 90]]


<h3 style="color:green;"> Matrices Product </h3>

To find matrices product we use '@' operator or dot() function

In [52]:
#Example: Using '@' operaror 
arr1=np.arange(2,11)
arr1=np.reshape(arr1,(3,3))
arr2=np.arange(1,10)
arr2=np.reshape(arr2,(3,3))
print(arr1,arr2,arr1@arr2,sep="\n")

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 42  51  60]
 [ 78  96 114]
 [114 141 168]]


In [53]:
#Example: using dot() function
arr1=np.arange(2,11)
arr1=np.reshape(arr1,(3,3))
arr2=np.arange(1,10)
arr2=np.reshape(arr2,(3,3))
print(arr1,arr2,arr1.dot(arr2),sep="\n")

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 42  51  60]
 [ 78  96 114]
 [114 141 168]]


<h3 style="color:green;"> Other Operators on numpy array </h3>

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one

In [54]:
import numpy as np
rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
print((a))
b += a
print(b)

[[3 3 3]
 [3 3 3]]
[[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


Since, the result is stored in an existing array then when we try to add an array of different data types, then it may cause an error. Let's see

In [56]:
import numpy as np
rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3      #a is in integer array
b += a      #b is a floting point array
a += b  #the data type of existing array 'a' cannot be changed from integer to floating point

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

<h3 style="color:green;"> Upcasting </h3>

When you perform operations on arrays that have different data types, NumPy tries to be smart about deciding the data type of the resulting array. It chooses a data type that is more general or precise to accommodate the values of both original arrays. 

In [59]:
#Example 
arr1=np.ones(3,dtype=np.int32)
arr2=np.linspace(1,3.14,3)
print(arr2.dtype)
arr3=arr1+arr2     #data type of arr3 is float64 so it iscapable of holding values of both arrays
print(arr3.dtype)
arr4=np.exp(arr3*1j)
print(arr4.dtype)

float64
float64
complex128


#### Takeaways from the above example

np.exp(): This is the exponential function in NumPy. When applied to an array, it calculates the exponential (e^x) of each element in the array.

1j: In Python, 1j represents the imaginary unit, which is the square root of -1. It's used to create complex numbers.

<h3 style="color:green;"> Uniary operation as method inplementation in numpy array </h3>

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [60]:
#Example 
import numpy as np
arr1=np.arange(5,14)
arr1=np.reshape(arr1,(3,3))
print(arr1)
#sum()
print(" Sum : ", arr1.sum())
#min()
print(" Min : ", arr1.min())
#max()
print("Max : ", arr1.max())

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
 Sum :  81
 Min :  5
Max :  13


By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array:

In [61]:
import numpy as np
arr1=np.arange(1,10)
arr1=np.reshape(arr1,(3,3))
print(arr1)
#sum()
print(" Sum along axis 0: ", arr1.sum(axis=0))
#min()
print(" Min along axis axis 1: ", arr1.min(axis=1))
#max()
print("Max along axis 1 : ", arr1.max())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 Sum along axis 0:  [12 15 18]
 Min along axis axis 1:  [1 4 7]
Max along axis 1 :  9


In [62]:
#Example 
import numpy as np
arr=np.array([[np.arange(1,4),np.arange(4,7)],[np.arange(7,10),np.arange(10,13)]])
print(f"It is a {arr.ndim}D array. Vaues are: ")
print(arr)
#Sum along different axis
print("Sum along axis 0 : ", arr.sum(axis=0))
print("Sum along axis 1 : ", arr.sum(axis=1))
print("Sum along axis 2 : ", arr.sum(axis=2))
#cumumlative sum, cumsum()
print("Cumulative Sum along axis 0 : ", arr.cumsum(axis=0))
print("Cumulative Sum along axis 1 : ", arr.cumsum(axis=1))
print("Cumulative Sum along axis 2 : ", arr.cumsum(axis=2))

It is a 3D array. Vaues are: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Sum along axis 0 :  [[ 8 10 12]
 [14 16 18]]
Sum along axis 1 :  [[ 5  7  9]
 [17 19 21]]
Sum along axis 2 :  [[ 6 15]
 [24 33]]
Cumulative Sum along axis 0 :  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 8 10 12]
  [14 16 18]]]
Cumulative Sum along axis 1 :  [[[ 1  2  3]
  [ 5  7  9]]

 [[ 7  8  9]
  [17 19 21]]]
Cumulative Sum along axis 2 :  [[[ 1  3  6]
  [ 4  9 15]]

 [[ 7 15 24]
  [10 21 33]]]


## Visualization 

### Figure 1: 3D Array
<img src="https://github.com/SimmiSheetalJain/Medias_for_notes_and_blogs/blob/main/3D-Array.jpg?raw=true" width=70% height=30%>

### Figure 2: Axis 0
<img src="https://github.com/SimmiSheetalJain/Medias_for_notes_and_blogs/blob/main/Axis%200.jpg?raw=true" width=70% height=30%>

### Figure 3: Axis 1
<img src="https://github.com/SimmiSheetalJain/Medias_for_notes_and_blogs/blob/main/Axis_1.jpg?raw=true" width=70% height=30%>

### Figure 4: Axis 2
<img src="https://github.com/SimmiSheetalJain/Medias_for_notes_and_blogs/blob/main/Axis_2.jpg?raw=true" width=70% height=30%>

<h2 style="color:#eb3477">Question1: Create a 2D array from list of lists and Find the minimum value along each of the three rows</h2>
<h3 style="color:#eb3477">List1=[[110,102,183],[40,175,106],[192,40,195]]</h3>

In [63]:
import numpy as np
List1=[[110,102,183],[40,175,106],[192,40,195]]
arr=np.array(List1)
minimum_along_row=arr.min(axis=1)
print("Minimum along first row : ",minimum_along_row[0])
print("Minimum along second row : ",minimum_along_row[1])
print("Minimum along third row : ",minimum_along_row[2])

Minimum along first row :  102
Minimum along second row :  40
Minimum along third row :  40


# Basic indexing and slicing

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [64]:
#example 
import numpy as np
arr=np.arange(10)
#E.G.
print(arr[2:5])
#E.G.
print(arr[2:])
#E.G.
print(arr[:])
#E.G.
print(arr[::-1])
#E.G.
print(arr[1:9:2])
#E.G.
arr[:6:2]=20
print(arr)
#E.G.
for i in arr:
    print(format(i**(1/3),".2f"))

[2 3 4]
[2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
[1 3 5 7]
[20  1 20  3 20  5  6  7  8  9]
2.71
1.00
2.71
1.44
2.71
1.71
1.82
1.91
2.00
2.08


Multidimensional arrays can have one index per axis. These indices are given in the subscript operator separated by commas:

In [65]:
#Example 1:
import numpy as np
List1=[[110,102,183],[40,175,106],[192,40,195]]
arr=np.array(List1)
#E.G.
print(arr[0:2,1:])

[[102 183]
 [175 106]]


In [66]:
#Example 2:
import numpy as np
List1=[[110,102,183],[40,175,106],[192,40,195]]
arr=np.array(List1)
#E.G.
print(arr[-2:-4:-1,:]) 

[[ 40 175 106]
 [110 102 183]]


In [67]:
#Example 3:
import numpy as np
List1=[[110,102,183],[40,175,106],[192,40,195]]
arr=np.array(List1)
#E.G.
print(arr[2,2]) 

195


When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

In [68]:
#Example
import numpy as np
List1=[[110,102,183],[40,175,106],[192,40,195]]
arr=np.array(List1)
#E.G.
print("When Second index is missing : ",arr[2,]) #Equivalent to arr[2,0:3]
print("When Second index is mentioned: ",arr[2,0:3])
print("When we want to slice out second column:\n ",arr[0:3,1:2])

When Second index is missing :  [192  40 195]
When Second index is mentioned:  [192  40 195]
When we want to slice out second column:
  [[102]
 [175]
 [ 40]]


<h3 style="color:green;"> Slicing on a 3D array (two stacked 2D arrays)</h3>

In [69]:
#Example 
import numpy as np
arr=np.array([[np.arange(1,4),np.arange(4,7)],[np.arange(7,10),np.arange(10,13)]])
print(f"It is a {arr.ndim}D array. Vaues are: ")
print(arr)
#E.G.
print(arr[0:2, 0:2,0:1])

It is a 3D array. Vaues are: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1]
  [ 4]]

 [[ 7]
  [10]]]


### Visualization
<img src="https://github.com/SimmiSheetalJain/Medias_for_notes_and_blogs/blob/main/Slicing_on_3D.jpg?raw=true"  width=70% height=30%>

<h3 style="color:green;">Iterating over multidimensional arrays </h3> 

Iterating over multidimensional arrys is as same as it is in other programming language. We loop first loop for the length of first dimention, second loop for length of second dimention and so on.

In [70]:
#Example 
import numpy as np
arr=np.array([[np.arange(1,4),np.arange(4,7)],[np.arange(7,10),np.arange(10,13)]])
print(f"It is a {arr.ndim}D array. Vaues are: ")
shape=arr.shape
for i in range(shape[0]):
    for j in range(shape[1]):
        for k in range(shape[2]):
            print(arr[i][j][k],end=" ")
        print()
    print()

It is a 3D array. Vaues are: 
1 2 3 
4 5 6 

7 8 9 
10 11 12 



# Boolean Indexing, Advanced indexing, and Index tricks 

NumPy offers more indexing facilities than regular Python sequences. In addition to indexing by integers and slices, as we saw before, arrays can be indexed by arrays of integers and arrays of booleans.

<h3 style="color:green;"> Indexing with Arrays of Indices </h3>

In [71]:
#Example 
import numpy as np
arr=np.random.randint(2,10,9)**2
print(arr)
i=np.array([1,2,3,5,6,7])
print(arr[i])        #print value at index mention in i 

[81 16 81  9 16 49 25 49  4]
[16 81  9 49 25 49]


##### When the indexed array arr is multidimensional, a single array of indices refers to the first dimension of arr.

In [72]:
import numpy as np
arr=np.reshape(np.arange(1,10),(3,3))
print("Array :\n",arr)
print("____________")
indices=np.reshape(np.random.randint(0,3,6),(2,-1))
print("____________")
result=arr[indices]
print("____________")
print(result)    

Array :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
____________
____________
____________
[[[7 8 9]
  [1 2 3]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [1 2 3]]]


##### In Python, arr[i, j] is exactly the same as arr[(i, j)]—so we can put i and j in a tuple and then do the indexing with that.

In [73]:
import numpy as np
arr=np.reshape(np.arange(1,10),(3,3))
print("Array :\n",arr)
i=[2,1,2];j=[2,0,1]
indices_tuple=(i,j)
print("Indices :\n",indices)
print("Array[indices]: \n",arr[indices_tuple])

Array :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Indices :
 [[2 0 2]
 [0 1 0]]
Array[indices]: 
 [9 4 8]


##### You can also use indexing with arrays as a target to assign to:

In [74]:
import numpy as np
arr=np.arange(5)
arr[[1,3,4]]=20
print(arr)

[ 0 20  2 20 20]


###### However, when the list of indices contains repetitions, the assignment is done several times, leaving behind the last value

In [75]:
import numpy as np
arr=np.arange(5,15,2)
print(arr)
arr[[1,1,4]]=20
print(arr)


[ 5  7  9 11 13]
[ 5 20  9 11 20]


In [205]:
#example 
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [11,12,13,14]])

In [206]:
#example 
arr2[1:]

array([[ 5,  6,  7,  8],
       [11, 12, 13, 14]])

In [216]:
#example 
arr2[2:,3:]

array([[14]])

<h2 style="color:#eb3477">Question 2: Create a numpy array form the given list of lists and Swap row 1 and row 2 in the given array</h2>
<h3 style="color:#eb3477">List1=[[110,102,183],[40,175,106],[192,40,195]]</h3>

In [76]:
#answer
import numpy as np
List1=[[110,102,183],[40,175,106],[192,40,195]]
arr=np.array(List1)
print("Original Array :\n",arr)
arr[0,1]=arr[1,0]
print("Array after swapping :\n",arr)

Original Array :
 [[110 102 183]
 [ 40 175 106]
 [192  40 195]]
Array after swapping :
 [[110  40 183]
 [ 40 175 106]
 [192  40 195]]


<h3 style="color:green;">Indexing with Boolean Arrays</h3>

When we index arrays with arrays of (integer) indices we are providing the list of indices to pick. With boolean indices the approach is different; we explicitly choose which items in the array we want and which ones we don’t.

In [77]:
#Example:
a = np.arange(12).reshape(3, 4)
print(a)
b = np.array([[False, False, False, False],
              [False,  True,  True,  True],
              [ True,  True,  True,  True]])
print(a[b]) # 1d array with the selected elements

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 5  6  7  8  9 10 11]


The second way of indexing with booleans is more similar to integer indexing; for each dimension of the array we give a 1D boolean array selecting the slices we want:



In [78]:
import numpy as np
arr=np.arange(12,24).reshape(3,4)
selecting_rows=np.array([False,True,True])                #the length of Selecting_rows is same as axis 0 of array arr
selecting_columns=np.array([True,False,False,True])       #the length of Selecting_columns is same as axis 1 of array arr 
print(arr[selecting_rows,:])
print(arr[:,selecting_columns])
print(arr[selecting_rows,selecting_columns])

[[16 17 18 19]
 [20 21 22 23]]
[[12 15]
 [16 19]
 [20 23]]
[16 23]


# Transposing Array and Swapping axes

<h3 style="color:green;"> Transposing an Array </h3>

In NumPy, you can transpose an array axes using the numpy.transpose() function.It is a universal function.

##### numpy.transpose(a, axes=None)

In [79]:
#Example:
import numpy as np
arr1=np.random.randint(2,25,9)
arr1=np.reshape(arr1,(3,3))
print("Orginal matrix :\n", arr1)
print("Transpose of the orgininal matrix :\n", np.transpose(arr1))

Orginal matrix :
 [[ 2 24 21]
 [13 12  9]
 [14 21 11]]
Transpose of the orgininal matrix :
 [[ 2 13 14]
 [24 12 21]
 [21  9 11]]


<h3 style="color:green;"> Swaping of axes in an Array </h3>

The numpy.swapaxes() method allows you to swap two axes of an array. You specify the axes you want to swap.

###### numpy.swapaxes(arr, axis1, axis2)


In [80]:
import numpy as np
arr=np.array([[np.arange(1,4),np.arange(4,7)],[np.arange(7,10),np.arange(10,13)]])
print(f"It is a {arr.ndim}D array. Vaues are: ")
print(arr)
print(np.swapaxes(arr,0,2))

It is a 3D array. Vaues are: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


# Universal Functions

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions” (ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

<h3 style="color:green;">Here is the list of several universal functions used in numpy</h3>

1. __all__: Tests whether all array elements along a given axis evaluate to True.
2. __any:__ Tests whether any array element along a given axis evaluates to True.
3. __apply_along_axis:__ Applies a function along a specified axis of an array.
4. __argmax:__ Returns the indices of the maximum values along an axis.
5. __argmin:__ Returns the indices of the minimum values along an axis.
6. __argsort:__ Returns the indices that would sort an array.
7. __average:__ Computes the weighted average along a specified axis.
8. __bincount:__ Counts occurrences of each value in an array of non-negative integers.
9. __ceil:__ Computes the ceiling of each element.
10. __clip:__ Limits the values in an array to be within a specified range.
11. __conj:__ Returns the complex conjugate.
12. __corrcoef:__ Computes the correlation coefficient between two arrays.
13. __cov:__ Computes the covariance matrix for two or more arrays.
14. __cross:__ Computes the cross product of two vectors.
15. __cumprod:__ Computes the cumulative product of elements along a given axis.
16. __cumsum:__ Computes the cumulative sum of elements along a given axis.
17. __diff:__ Computes the difference between consecutive elements.
18. __dot:__ Computes the dot product of two arrays.
19. __floor:__ Computes the floor of each element.
20. __inner:__ Computes the inner product of two arrays.
21. __invert:__ Computes the bit-wise inversion of an array.
22. __lexsort:__ Performs an indirect sort on multiple keys.
23. __max:__ Returns the maximum value along a specified axis.
24. __maximum:__ Element-wise maximum of two arrays.
25. __mean:__ Computes the arithmetic mean along a specified axis.
26. __median:__ Computes the median along a specified axis.
27. __min:__ Returns the minimum value along a specified axis.
28. __minimum:__ Element-wise minimum of two arrays.
29. __nonzero:__ Returns the indices of non-zero elements.
30. __outer:__ Computes the outer product of two vectors.
31. __prod:__ Computes the product of elements along a given axis.
32. __re:__ Returns the real part of the complex argument.
33. __round:__ Rounds each element to the nearest integer.
34. __sort:__ Returns a sorted copy of an array.
35. __std:__ Computes the standard deviation along a specified axis.
36. __sum:__ Computes the sum of elements along a specified axis.
37. __trace:__ Computes the sum along the diagonal of an array.
38. __transpose:__ Permutes the dimensions of an array.
39. __var:__ Computes the variance along a specified axis.
40. __vdot:__ Computes the dot product of two vectors.
41. __vectorize:__ Converts a Python function into a NumPy vectorized function.
42. __where:__ Returns elements chosen from x or y depending on condition.

#### argmax(), argmin()

In [81]:
import numpy as np
arr=np.array([[5,2,3,9,13],[4,1,6,11,12]])
print(np.argmax(arr, axis=0))
print(np.argmin(arr, axis=0))

[0 0 1 1 0]
[1 1 0 0 1]


#### numpy.argsort(a, axis=-1, kind=None, order=None)

here,<br>
=> a: is array to be sorted <br>
=> axis: is the axis along which to sort. The default is -1 (the last axis). If None, the flattened array is used.<br>
=> kind: {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}, optional.The default is ‘quicksort’ <br>
=> order: str or list of str, optional.When a is an array with fields defined, this argument specifies which fields to compare first, second, etc. A single field can be specified as a string, and not all fields need be specified, but unspecified fields will still be used, in the order in which they come up in the dtype, to break ties.<br>

In [82]:
import numpy as np
arr=np.array([[5,2,3,9,13],[4,1,6,11,12]])
print(np.argsort(arr)) #Returns the indices that would sort an array.

[[1 2 0 3 4]
 [1 0 2 3 4]]


#### numpy.average(a, axis=None, weights=None, returned=False, *, keepdims=<no value>)

In [83]:
import numpy as np
data = np.arange(6).reshape((2, 3))
print(data)
print(np.round(np.average(data, axis=0, weights=[1/4, 3/4]),2))
print(np.round(np.average(data, axis=1, weights=[1/4, 3/4,5/4]),2))

[[0 1 2]
 [3 4 5]]
[2.25 3.25 4.25]
[1.44 4.44]


#### numpy.bincount(x, /, weights=None, minlength=0) 

the numpy.bincount() function is used to count the occurrences of non-negative integers in an array. It is particularly useful for counting the occurrences of each integer in a set of non-negative integers.

In [84]:
import numpy as np
arr=np.random.randint(2,5,10)
print(arr)
print(np.bincount(arr))

[3 4 3 4 2 2 4 3 2 3]
[0 0 3 4 3]


The output [0 0 1 6 3] corresponds to the counts of occurrences for each unique integer in the array generated by np.random.randint(2, 5, 10).\
The number 0 appears 0 times.\
The number 1 appears 0 times.\
The number 2 appears 1 time.\
The number 3 appears 6 times.\
The number 4 appears 3 times.

#### numpy.clip(a, a_min, a_max, out=None, **kwargs)

the clip() function is used to limit the values in an array to a specified range. It takes three arguments: an array, a minimum value, and a maximum value. The function returns a new array with values clipped to be within the specified range.

In [85]:
#Example 
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original Array:\n",arr)
# Clip values in the array to be between 3 and 7
clipped_arr = np.clip(arr, 3, 7)
print("",clipped_arr)

Original Array:
 [1 2 3 4 5 6 7 8 9]
 [3 3 3 4 5 6 7 7 7]


#### maximum: Element-wise maximum of two arrays.

In [86]:
import numpy as np
arr1=np.random.randint(2,25,9)
arr1=np.reshape(arr1,(3,3))
arr2=np.random.randint(2,25,9)
arr2=np.reshape(arr2,(3,3))
result=np.maximum(arr1,arr2)
print(arr1)
print(arr2)
print(result)

[[24 17 15]
 [ 6 13 24]
 [14 16  6]]
[[12 13 23]
 [ 2 17 17]
 [ 5  7 18]]
[[24 17 23]
 [ 6 17 24]
 [14 16 18]]


#### numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)

In [87]:
import numpy as np
a = np.array([[5, 9, 13], [14, 10, 12], [11, 15, 19]])
print(np.mean(a,axis=1))

[ 9. 12. 15.]


#### numpy.prod(a, axis=None, dtype=None, keepdims=False)

the prod() function is used to compute the product of array elements along a specified axis or the flattened array. The syntax for the prod() function is as follows:

In [88]:
import numpy as np
a = np.array([[5, 9, 13], [14, 10, 12], [11, 15, 19]])
print(np.prod(a,axis=0))

[ 770 1350 2964]


#### numpy.sort(a, axis=-1, kind=None, order=None)

a: The input array to be sorted.\
axis (optional): Axis along which to sort. By default, the array is flattened before sorting.\
kind (optional): Sorting algorithm. It can take values like 'quicksort', 'mergesort', or 'heapsort'. The default is 'quicksort'.\
order (optional): If the array contains fields, this parameter specifies which fields to use when sorting.\

In [89]:
import numpy as np
a = np.array([[5, 9, 13], [14, 10, 12], [11, 15, 19]])
print(np.sort(a,axis=1,kind="mergesort"))

[[ 5  9 13]
 [10 12 14]
 [11 15 19]]


#### You can use numpy.trace() to calculate the sum of the diagonal elements of a matrix.

In [90]:
#Example:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

trace_value = np.trace(matrix)

print(trace_value)


15


#### numpy.transpose(a, axes=None)

It returns a view of the array with axes transposed. The transpose operation essentially swaps the dimensions of the array.

In [91]:
import numpy as np
arr1=np.random.randint(2,25,9)
arr1=np.reshape(arr1,(3,3))
print("Orginal matrix :\n", arr1)
print("Transpose of the orgininal matrix :\n", np.transpose(arr1))

Orginal matrix :
 [[12 23 24]
 [ 6 20 23]
 [ 2 19  7]]
Transpose of the orgininal matrix :
 [[12  6  2]
 [23 20 19]
 [24 23  7]]


#### numpy.where(condition, [x, y, ]/)

numpy.where() function is used to return the indices of elements in an input array that satisfy a certain condition.

In [92]:
import numpy as np
arr1=np.random.randint(2,25,9)
arr1=np.reshape(arr1,(3,3))
print("Orginal matrix :\n", arr1)
print(f"Updated Array : \n", np.where(arr1 > 10, a, 1 ))

Orginal matrix :
 [[ 5 23  4]
 [11 19  4]
 [11  7  6]]
Updated Array : 
 [[ 1  9  1]
 [14 10  1]
 [11  1  1]]


Other than these common function, numpy provides hundreds of functions for performing operations on arrays. Here are some commonly used functions:


* Mathematics: `np.sum`, `np.exp`, `np.round`, arithemtic operators 
* Array manipulation: `np.reshape`, `np.stack`, `np.concatenate`, `np.split`
* Linear Algebra: `np.matmul`, `np.dot`, `np.transpose`, `np.eigvals`
* Statistics: `np.mean`, `np.median`, `np.std`, `np.max`

> **How to find the function you need?** The easiest way to find the right function for a specific operation or use-case is to do a web search. For instance, searching for "How to join numpy arrays" leads to [this tutorial on array concatenation](https://cmdlinetips.com/2018/04/how-to-concatenate-arrays-in-numpy/). 

You can find a full list of array functions here: https://numpy.org/doc/stable/reference/routines.html

<h2 style="color:#eb3477">Question 3: Create a numpy array form the given list of lists and Replace all the odd numbers in the array with -2</h2>
<h3 style="color:#eb3477">List1=[[110,102,183],[40,175,106],[192,40,195]]</h3>

In [93]:
#Answer
import numpy as np
List1=[[110,102,183],[40,175,106],[192,40,195]]
arr=np.array(List1)
print(arr)
arr=np.where(arr%2!=0,-2,arr)
print(arr)

[[110 102 183]
 [ 40 175 106]
 [192  40 195]]
[[110 102  -2]
 [ 40  -2 106]
 [192  40  -2]]


# Array-Oriented Programming With Arrays

A topic that is better to study after learning use of numpy with panda, matplotlib, seaborn, and other data sciecne library

# Conditional Logic as Arrays Operations

 ## 1. Using np.where():

In [94]:
#Example 
import numpy as np
arr=np.random.randint(2,17,15).reshape(3,5)
print("Orginial Array:\n", arr)
new_arr=np.where(arr<10,arr,0)
print("New Array:\n",new_arr)

Orginial Array:
 [[ 9 15  3  3 12]
 [10 14 14  8 11]
 [12  8  3 12  9]]
New Array:
 [[9 0 3 3 0]
 [0 0 0 8 0]
 [0 8 3 0 9]]


## 2. Using Boolean Indexing:

In [95]:
import numpy as np
List1=[[110,102,183],[40,175,106],[192,40,195]]
arr=np.array(List1)
print(arr)
condition=(arr%2==0)
print("\nElement that satisfies condition:\n\n", arr[condition])

[[110 102 183]
 [ 40 175 106]
 [192  40 195]]

Element that satisfies condition:

 [110 102  40 106 192  40]


## 3. Applying Multiple Conditions:

In [96]:
#Example 1
import numpy as np
arr=np.random.randint(2,17,15).reshape(3,5)
print("Orginial Array:\n", arr)
condition=np.logical_and(arr%3!=0, arr%5!=0)
new_arr=np.where(condition,arr,0)
print("New Array:\n",new_arr)

Orginial Array:
 [[14  5  5  3  9]
 [ 6  7  6 10  5]
 [ 2 15  7  3  3]]
New Array:
 [[14  0  0  0  0]
 [ 0  7  0  0  0]
 [ 2  0  7  0  0]]


In [97]:
#Example 2
import numpy as np
arr=np.random.randint(2,17,15).reshape(3,5)
print("Orginial Array:\n", arr)
condition=np.logical_and(arr%3!=0, arr%5!=0)
print("New Array:\n",arr[condition])

Orginial Array:
 [[ 4  9 12  5  6]
 [ 7  7  6  2 13]
 [12 10 16 13 16]]
New Array:
 [ 4  7  7  2 13 16 13 16]


## 4. Element-wise Comparison:

#### Printing intersection of two arrays

In [98]:
#Example1: printing intersection of two arrays
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 2, 3, 4, 4])
result = (arr1 == arr2)
print(arr1[result])

[2 3 4]


## 5. Conditional Assignment:

In [99]:
#Example 2
import numpy as np
arr=np.random.randint(2,17,15).reshape(3,5)
print("Orginial Array:\n", arr)
print("New Array:\n",arr[arr%2==0])

Orginial Array:
 [[10 10 11  9 11]
 [14 13 13 15 10]
 [10  2  5  7 13]]
New Array:
 [10 10 14 10 10  2]


## 6. Using np.select() for Multiple Conditions:

#### np.select() allows you to choose values from multiple arrays based on multiple conditions.

In [100]:
#example 1:
import numpy as np
arr=np.arange(2,20).reshape(3,6)
condition=[arr>10,arr%12!=0,arr>5]
arrays=[arr,arr**2,arr**1/2]
result=np.select(condition,arrays)       #Now, there will be three arrays
print(result)

[[  4.   9.  16.  25.  36.  49.]
 [ 64.  81. 100.  11.  12.  13.]
 [ 14.  15.  16.  17.  18.  19.]]


## 7. Handling NaN Values:

In [101]:
import numpy as np
arr = np.array([1.0, np.nan, 3.0, np.nan, 5.0])
boolean_index=np.where(np.isnan(arr),False,True)
print(arr[boolean_index])

[1. 3. 5.]


# File Input and Output With Array.

We can generate an array from a file.To generate data from text file, we can use genfromtxt. The syntax is as follows:

numpy.genfromtxt(fname, dtype=float, comments='#', delimiter=None,<br> 
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;skip_header=0, skip_footer=0, converters=None,<br>  
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;missing_values=None, filling_values=None, usecols=None,<br>  
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;names=None, excludelist=None, deletechars=None,<br>  
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;replace_space='_', autostrip=False, case_sensitive=True,<br>  
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;defaultfmt='f%i', unpack=None, usemask=False, loose=True,<br>  
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;invalid_raise=True, max_rows=None, encoding='bytes')<br> 


In a nutshell, genfromtxt runs two main loops. The first loop converts each line of the file in a sequence of strings. The second loop converts each string to the appropriate data type. This mechanism is slower than a single loop, but gives more flexibility. In particular, genfromtxt is able to take missing data into account, when other faster and simpler functions like loadtxt cannot.

In [102]:
#Example
import numpy as np
from io import StringIO
with open("file.txt","r") as f:
    data=f.read()
    print(data)
    arr=np.genfromtxt(StringIO(data), delimiter=" ", dtype=None,encoding='utf-8')
print(arr)

Anjali Jain
Ravi Jain
Shubh Jain
Sheetal Jain

[['Anjali' 'Jain']
 ['Ravi' 'Jain']
 ['Shubh' 'Jain']
 ['Sheetal' 'Jain']]


<h3 style="color:green;">Defining the input</h3>

The only mandatory argument of genfromtxt is the source of the data. It can be a string, a list of strings, a generator or an open file-like object with a read method, for example, a file or io.StringIO object. If a single string is provided, it is assumed to be the name of a local or remote file. If a list of strings or a generator returning strings is provided, each string is treated as one line in a file. When the URL of a remote file is passed, the file is automatically downloaded to the current directory and opened.

In [103]:
#Example
import numpy as np
from io import StringIO
data="Ansh and Aaradhya are two good students of mine"
arr=np.genfromtxt(StringIO(data), delimiter=" ", dtype=None,encoding='utf-8')
print(arr)

['Ansh' 'and' 'Aaradhya' 'are' 'two' 'good' 'students' 'of' 'mine']


<h3 style="color:green;">Splitting the lines into columns</h3>

#### 1. The delimiter argument
The delimiter keyword is used to define how the splitting should take place.Quite often, a single character marks the separation between columns. For example, comma-separated files (CSV) use a comma (,) or a semicolon (;) as delimiter:

In [104]:
#Example
import numpy as np
from io import StringIO
data="12,13,14,15,16,17"
arr=np.genfromtxt(StringIO(data), delimiter=",", dtype=None,encoding='utf-8')
print(arr)

[12 13 14 15 16 17]


#### 2. The autostrip argument
By default, when a line is decomposed into a series of strings, the individual entries are not stripped of leading nor trailing white spaces. This behavior can be overwritten by setting the optional argument autostrip to a value of True:

In [105]:
#Example
import numpy as np
from io import StringIO
data="    Aastha is also a good students of mine.She is trying to work hard for boards         "
arr=np.genfromtxt(StringIO(data), delimiter=" ", dtype=None, encoding='utf-8',autostrip=False)
print("Autostripped Result :\n",arr)

Autostripped Result :
 ['Aastha' 'is' 'also' 'a' 'good' 'students' 'of' 'mine.She' 'is' 'trying'
 'to' 'work' 'hard' 'for' 'boards']


As it can be seen, autostip argument has removed leading and traling whitespaces when it is kept True.

#### 3. The comments argument

The optional argument comments is used to define a character string that marks the beginning of a comment. By default, genfromtxt assumes comments='#'. Any character present after the comment marker(s) is simply ignored.

In [106]:
#Example 
import numpy as np
data = u"""#This is how comment argument works
# Skip me !
# Skip me too !
1, 2
3, 4
5, 6 #This is the third line of the data
7, 8
# And here comes the last line
9, 0
"""
print(np.genfromtxt(StringIO(data), comments="#", delimiter=","))

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]
 [9. 0.]]


<h3 style="color:green;">Skipping lines and choosing columns</h3>

#### 1. The skip_header and skip_footer arguments

The presence of a header in the file can hinder data processing. In that case, we need to use the skip_header optional argument. The values of this argument must be an integer which corresponds to the number of lines to skip at the beginning of the file, before any other action is performed. Similarly, we can skip the last n lines of the file by using the skip_footer attribute and giving it a value of n

In [107]:
#Example
import numpy as np
from io import StringIO
with open("thematrix.txt","r") as f:
    data=f.read(500)
    print(data)
    arr=np.genfromtxt(StringIO(data), delimiter="\n", dtype=None,encoding='utf-8', skip_header=2,skip_footer=5)
print("\n\nThe obtained string array is: \n\n",arr)

Important insights:
#Residual Self-image: It is the mental 
projection of your digital self

#How do you define, what is real?
What you can feel, smell, taste, and see is real 
Then see real is simply electrical signals
interpreted by your brain

#The world exists only as part of a 
neural-interactive simulation, that we call 
the matrix. 

#The world in 2199 will be a horrible world

#We all are now united in celebration. 
we are marvelled at our own magnificence
as we gave birth to AI.

#AI: A


The obtained string array is: 

 ['projection of your digital self'
 'What you can feel, smell, taste, and see is real'
 'Then see real is simply electrical signals']


#### 2.The usecols argument

In some cases, we are not interested in all the columns of the data but only a few of them. We can select which columns to import with the usecols argument. This argument accepts a single integer or a sequence of integers corresponding to the indices of the columns to import. Remember that by convention, the first column has an index of 0. Negative integers behave the same as regular Python negative indexes.

In [108]:
#Example
import numpy as np
from io import StringIO
data = u"1 2 3\n4 5 6"
print(np.genfromtxt(StringIO(data), usecols=(0, -1)))

[[1. 3.]
 [4. 6.]]


<h3 style="color:green">Choosing the data type</h3>

The main way to control how the sequences of strings we have read from the file are converted to other types is to set the dtype argument. Acceptable values for this argument are:

#### 1. A single type, such as dtype=float. The output will be 2D with the given dtype, unless a name has been associated with each column with the use of the names argument

In [109]:
#example
import numpy as np
from io import StringIO
data = StringIO("1 2 3\n 4 5 6")
np.genfromtxt(data, names="A, B, C")

array([(1., 2., 3.), (4., 5., 6.)],
      dtype=[('A', '<f8'), ('B', '<f8'), ('C', '<f8')])

#### 2. A sequence of types, such as dtype=(int, float, float).

In [110]:
#example
import numpy as np
from io import StringIO
data = StringIO("1 2 3\n 4 5 6")
np.genfromtxt(data, dtype=(int, float, int))

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('f0', '<i4'), ('f1', '<f8'), ('f2', '<i4')])

#### 3. A comma-separated string, such as dtype="i4,f8,|U3".

#### 4. A dictionary with two keys 'names' and 'formats'.

#### 5. A sequence of tuples (name, type), such as dtype=[('A', int), ('B', float)].

In [111]:
#example
import numpy as np
from io import StringIO
data = StringIO("1 2 3\n 4 5 6")
ndtype=[('a',int), ('b', float), ('c', int)]
names = ["A", "B", "C"]
np.genfromtxt(data, names=names, dtype=ndtype)

array([(1, 2., 3), (4, 5., 6)],
      dtype=[('A', '<i4'), ('B', '<f8'), ('C', '<i4')])

#### 6. An existing numpy.dtype object.

#### 7. the special value None. In that case, the type of the columns will be determined from the data itself.

In all the cases but the first one, the output will be a 1D array with a structured dtype. This dtype has as many fields as items in the sequence. The field names are defined with the names keyword.

# Broadcasting

There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes. For example, you have an array that contain height in meter. But if you want to convert the given height into inches, then you can multiply the height value by 39.37.NumPy understands that the multiplication should happen with each cell. That concept is called broadcasting. 

Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. The dimensions of your array must be compatible, for example, when the dimensions of both arrays are equal or when one of them is 1. If the dimensions are not compatible, you will get a ValueError.

In [112]:
#Example:
import numpy as np
heights=np.array([1.2,1.4,1.5,1.6])
print(heights)
convert_into_inches=heights*39.37
print(convert_into_inches)

[1.2 1.4 1.5 1.6]
[47.244 55.118 59.055 62.992]


In [199]:
arr4=np.random.randint(1,16,15).reshape(3,5)
arr5=np.arange(2,7)
print(arr4,arr5,arr4+arr5,sep="\n\n")

[[11  7 11  8 11]
 [ 2 12  7  7  2]
 [10  8  6  8  1]]

[2 3 4 5 6]

[[13 10 15 13 17]
 [ 4 15 11 12  8]
 [12 11 10 13  7]]


Since ,the size of arr5 is not compatible with size of arr4, it replicates its rows to match the shape

When the expression `arr4 + arr5` is evaluated, `arr5` (which has the shape `(5,)`) is replicated three times to match the shape `(3, 5)` of `arr4`. Numpy performs the replication without actually creating three copies of the smaller dimension array, thus improving performance and using lower memory.

<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png" width="360">

#### Note: Broadcasting only works if one of the arrays can be replicated to match the other array's shape else ti will be give an error

In [201]:
#Example 
arr6 = np.array([[7,8],
                 [9,10],
                 [11,12]])
arr4+arr6

ValueError: operands could not be broadcast together with shapes (3,5) (3,2) 

# View vs Copy

### 1. numpy.ndarray.view

#### method
&emsp;&emsp;ndarray.view([dtype][, type])

In [113]:
#example 
import numpy as np
arr=np.arange(2,10)
arr_view=arr.view()
print("Array : ",arr)
print("Array View : ",arr_view)

Array :  [2 3 4 5 6 7 8 9]
Array View :  [2 3 4 5 6 7 8 9]


#### Important Point
✦ Any changes made on view will reflect on original array.\
✦ View doesn't own array data. It creats a view with same data type.

In [114]:
#Example 
import numpy as np
arr=np.arange(2,10)
arr_view=arr.view()
arr_view[4]=100
print("Array : ",arr)
print("Array View : ",arr_view)

Array :  [  2   3   4   5 100   7   8   9]
Array View :  [  2   3   4   5 100   7   8   9]


#### 2. numpy.ndarray.copy

#### method
&emsp;&emsp;&emsp;ndarray.copy(order='C')

It Return a copy of the array.\
Parameters order{‘C’, ‘F’, ‘A’, ‘K’} is optional.

In [115]:
#Example
import numpy as np
arr=np.arange(2,10)
arr_view=arr.copy()
print("Array : ",arr)
print("Copied Array : ",arr_view)

Array :  [2 3 4 5 6 7 8 9]
Copied Array :  [2 3 4 5 6 7 8 9]


#### Important Point
✦ Any changes made on copied array will not reflect on original array.\
✦ Copied array owns a copy of original array. It creats a copy in a separate memory location.

In [116]:
#Example 
import numpy as np
arr=np.arange(2,10)
arr_view=arr.copy()
arr_view[5]=100
print("Array : ",arr)
print("Copied Array after changing a value : \n",arr_view)

Array :  [2 3 4 5 6 7 8 9]
Copied Array after changing a value : 
 [  2   3   4   5   6 100   8   9]


# Joining and Stacking Arrays

### 1.  concatenate()

In [117]:
#Example: Without specifying any axis
import numpy as np
arr1=np.arange(2,11).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
arr_new=np.concatenate((arr1,arr2))
print(arr1,end="\n\n")
print(arr2,end="\n\n")
print(arr_new,end="\n\n")
print("Shape : ", arr_new.shape)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

[[11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

Shape :  (6, 3)


In [118]:
#Example: with specifying axis
import numpy as np
arr1=np.arange(2,11).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
arr_new=np.concatenate((arr1,arr2), axis=1)
print(arr1,end="\n\n")
print(arr2,end="\n\n")
print(arr_new,end="\n\n")

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

[[11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 2  3  4 11 12 13]
 [ 5  6  7 14 15 16]
 [ 8  9 10 17 18 19]]



### 2. stack function

In [119]:
#Example: Without specifying any axis
import numpy as np
arr1=np.arange(2,11).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
arr_new=np.stack((arr1,arr2))
print(arr1,end="\n\n")
print(arr2,end="\n\n")
print(arr_new,end="\n\n")
print("Shape : ",arr_new.shape)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

[[11 12 13]
 [14 15 16]
 [17 18 19]]

[[[ 2  3  4]
  [ 5  6  7]
  [ 8  9 10]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]

Shape :  (2, 3, 3)


In [120]:
#Example: Without specifying any axis
import numpy as np
arr1=np.arange(2,11).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
arr_new=np.stack((arr1,arr2), axis=1)
print(arr1,end="\n\n")
print(arr2,end="\n\n")
print(arr_new,end="\n\n")
print("Shape : ",arr_new.shape)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

[[11 12 13]
 [14 15 16]
 [17 18 19]]

[[[ 2  3  4]
  [11 12 13]]

 [[ 5  6  7]
  [14 15 16]]

 [[ 8  9 10]
  [17 18 19]]]

Shape :  (3, 2, 3)


### Other varities of stack function

In [121]:
#Example1: hstack 
import numpy as np
arr1=np.arange(2,11).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
arr_new=np.hstack((arr1,arr2))
print(arr1,end="\n\n")
print(arr2,end="\n\n")
print(arr_new,end="\n\n")
print("Shape : ",arr_new.shape)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

[[11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 2  3  4 11 12 13]
 [ 5  6  7 14 15 16]
 [ 8  9 10 17 18 19]]

Shape :  (3, 6)


In [122]:
#Example2: vstack 
import numpy as np
arr1=np.arange(2,11).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
arr_new=np.vstack((arr1,arr2))
print(arr1,end="\n\n")
print(arr2,end="\n\n")
print(arr_new,end="\n\n")
print("Shape : ",arr_new.shape)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

[[11 12 13]
 [14 15 16]
 [17 18 19]]

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]
 [17 18 19]]

Shape :  (6, 3)


In [123]:
#Example3: dstack 
import numpy as np
arr1=np.arange(2,11).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
arr_new=np.dstack((arr1,arr2))
print(arr1,end="\n\n")
print(arr2,end="\n\n")
print(arr_new,end="\n\n")
print("Shape : ",arr_new.shape)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

[[11 12 13]
 [14 15 16]
 [17 18 19]]

[[[ 2 11]
  [ 3 12]
  [ 4 13]]

 [[ 5 14]
  [ 6 15]
  [ 7 16]]

 [[ 8 17]
  [ 9 18]
  [10 19]]]

Shape :  (3, 3, 2)


# Spliting an Array

In [124]:
#Example1:
import numpy as np
arr1=np.arange(2,11)
print("Original Array : \n\n",arr1)
ar=np.array_split(arr1,3)
print("\nSplitted List of Arrays : \n\n",ar)
for i in ar:
    print(i)

Original Array : 

 [ 2  3  4  5  6  7  8  9 10]

Splitted List of Arrays : 

 [array([2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]
[2 3 4]
[5 6 7]
[ 8  9 10]


In [125]:
#Example2:
import numpy as np
arr1=np.arange(2,11).reshape(3,3)
print("Original Array : \n\n",arr1)
ar=np.array_split(arr1,3,axis=1)
print("\nSplitted List of Arrays : \n\n",ar)
for i in ar:
    print(i)

Original Array : 

 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

Splitted List of Arrays : 

 [array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]]), array([[ 4],
       [ 7],
       [10]])]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]
[[ 4]
 [ 7]
 [10]]


# Frequently used array functions: shuffle, Unique, resize, flatten, ravel

### 1. Shuffle

In [126]:
#Example1:
import numpy as np
arr1=np.arange(2,11).reshape(3,3)
print("Original Array : \n\n",arr1)
np.random.shuffle(arr1)
print("\nShuffled Array: \n\n",arr1)

Original Array : 

 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

Shuffled Array: 

 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### 2. Unique

In [127]:
#Example
import numpy as np
data=np.random.randint(2,5,15)
print("Array : ", data)
element, occurrence = np.unique(data, return_counts=True)
dict_of_occ=dict(zip(element, occurrence))
for i, j in dict_of_occ.items():
    print(f"{i} occurs : {j} times")

Array :  [2 4 4 2 3 3 4 4 2 2 2 3 3 3 2]
2 occurs : 6 times
3 occurs : 5 times
4 occurs : 4 times


### 3. Resize

In [128]:
import numpy as np
data=np.random.randint(2,10,15)
print("Array : ", data)
var=np.resize(data, (3,5))
print("Resized Array : \n", var)

Array :  [3 2 3 7 3 6 5 9 2 6 4 4 5 8 8]
Resized Array : 
 [[3 2 3 7 3]
 [6 5 9 2 6]
 [4 4 5 8 8]]


### 4. Flatten 
method<br>
&emsp;&emsp;&emsp;ndarray.flatten(order='C')<br>
It Returns a copy of the array collapsed into one dimension.

#### Parameters: order{‘C’, ‘F’, ‘A’, ‘K’}, optional<br>
‘C’ means to flatten in row-major (C-style) order. ‘F’ means to flatten in column-major (Fortran- style) order. ‘A’ means to flatten in column-major order if a is Fortran contiguous in memory, row-major order otherwise. ‘K’ means to flatten a in the order the elements occur in memory. The default is ‘C’.

In [129]:
import numpy as np
data=np.random.randint(2,10,15).reshape(3,5)
print("Array : ", data)
print("Flattened Array : \n", data.flatten())
print("Array : ", data)
print("Flattened Array : \n", data.flatten(order="F"))
print("Array : ", data)
print("Flattened Array : \n", data.flatten(order="A"))
print("Array : ", data)
print("Flattened Array : \n", data.flatten(order="K"))

Array :  [[7 5 6 6 9]
 [9 5 4 4 7]
 [5 6 8 6 9]]
Flattened Array : 
 [7 5 6 6 9 9 5 4 4 7 5 6 8 6 9]
Array :  [[7 5 6 6 9]
 [9 5 4 4 7]
 [5 6 8 6 9]]
Flattened Array : 
 [7 9 5 5 5 6 6 4 8 6 4 6 9 7 9]
Array :  [[7 5 6 6 9]
 [9 5 4 4 7]
 [5 6 8 6 9]]
Flattened Array : 
 [7 5 6 6 9 9 5 4 4 7 5 6 8 6 9]
Array :  [[7 5 6 6 9]
 [9 5 4 4 7]
 [5 6 8 6 9]]
Flattened Array : 
 [7 5 6 6 9 9 5 4 4 7 5 6 8 6 9]


### 5. Ravel

#### method
&emsp;&emsp;&emsp;&emsp; numpy.ravel(a, order='C')

A 1-D array, containing the elements of the input, is returned. A copy is made only if needed.

In [130]:
import numpy as np
data=np.random.randint(2,10,15).reshape(3,5)
print("Array : ", data)
print("Flattened Array : \n", np.ravel(data))
print("Array : ", data)
print("Flattened Array : \n", np.ravel(data,order="F"))
print("Array : ", data)
print("Flattened Array : \n", np.ravel(data,order="K"))
print("Array : ", data)
print("Flattened Array : \n", np.ravel(data,order="A"))

Array :  [[8 8 3 9 6]
 [7 9 9 5 4]
 [5 7 9 4 9]]
Flattened Array : 
 [8 8 3 9 6 7 9 9 5 4 5 7 9 4 9]
Array :  [[8 8 3 9 6]
 [7 9 9 5 4]
 [5 7 9 4 9]]
Flattened Array : 
 [8 7 5 8 9 7 3 9 9 9 5 4 6 4 9]
Array :  [[8 8 3 9 6]
 [7 9 9 5 4]
 [5 7 9 4 9]]
Flattened Array : 
 [8 8 3 9 6 7 9 9 5 4 5 7 9 4 9]
Array :  [[8 8 3 9 6]
 [7 9 9 5 4]
 [5 7 9 4 9]]
Flattened Array : 
 [8 8 3 9 6 7 9 9 5 4 5 7 9 4 9]


# Transpose, Swapaxes, Inverse, Power, and Determinant of a Matrix using Numpy
Numpy library provides us a function to create a matrix as well as functions to find its transpose, inverse, determinant, etc. Let's see how they work

## 1. Transpose

In [131]:
#Example 
import numpy as np
m=np.matrix([[1,2],[3,4]])
print("Original Matrix : \n", m)
transpose=np.transpose(m)
print("Transpose Matrix : \n", transpose)

Original Matrix : 
 [[1 2]
 [3 4]]
Transpose Matrix : 
 [[1 3]
 [2 4]]


## 2.Swapaxes

In [132]:
#Example 
import numpy as np
m=np.matrix([[1,2],[3,4]])
print("Original Matrix : \n", m)
new_m=np.swapaxes(m,0,1)
print("New Matrix : \n", new_m)

Original Matrix : 
 [[1 2]
 [3 4]]
New Matrix : 
 [[1 3]
 [2 4]]


## 3.Inverse

### numpy.linalg.inv

linalg.inv(a) computes the (multiplicative) inverse of a matrix.

In [133]:
#Example: 
#Example 
import numpy as np
m=np.matrix([[1,2],[3,4]])
print("Original Matrix : \n", m)
inv_mat=np.linalg.inv(m)
print("Multiplicative inverse matrix : \n", inv_mat)

Original Matrix : 
 [[1 2]
 [3 4]]
Multiplicative inverse matrix : 
 [[-2.   1. ]
 [ 1.5 -0.5]]


## 4. numpy.linalg.matrix_power

linalg.matrix_power(a, n) Raises a square matrix to the (integer) power n.

In [134]:
#Example 
import numpy as np
m=np.matrix([[1,2],[3,4]])
print("Original Matrix : \n", m)
mp2=np.linalg.matrix_power(m,2)
print("Matrix raised to the power 2 : \n", mp2)

Original Matrix : 
 [[1 2]
 [3 4]]
Matrix raised to the power 2 : 
 [[ 7 10]
 [15 22]]


# 5. numpy.linalg.det

linalg.det(a) computes the determinant of an array

In [135]:
#Example 
import numpy as np
m=np.matrix([[1,2],[3,4]])
print("Original Matrix : \n", m)
det=np.linalg.det(m)
print("Determinant of a matrix : \n",format(det,".2f"))

Original Matrix : 
 [[1 2]
 [3 4]]
Determinant of a matrix : 
 -2.00


In [136]:
import numpy as np
List1=[[110,102,183],
       [40,175,106],
       [192,40,195]]
arr=np.array(List1)
second_column=arr[0:3,1:2]
for i in second_column:
    print(i)

[102]
[175]
[40]


# Practice 

## Practice Example on computation power of numpy array

Let's assume we want to know whether a place is good for growing apples or not. So, we need to know the temperature, humidity, and rainfall to determine whether the region is good for growing apples.
<br><br>
Let's say,
<br>
<br>
#### yield_of_apples= w1 * temperature + w2 * humidity + h3 * rainfall.
<br> 
<br>
We are expressing yield of apples as weighted sum of the temperature, humidity, and rainfall.This is an approximation. The actual relation may not be linear expression. But a simple linear model like this oftern works well in practice.
<br>
<br>
Based on some statistical analysis of historical data of the region's weather we can come up with more reasonable values for w1,w2, and w3. 

In [137]:
#Assigning weights
w1,w2,w3 = 0.2, 0.3, 0.5

Given some climate data for a region, we can now predict the yield of apples. Here's some sample data:

<img src="https://i.imgur.com/TXPBiqv.png" style="width:360px;">

To begin, we can define some variables to record climate data for a region.

In [138]:
# converting information into variables 
kanto_temp = 73
kanto_humidity = 43
kanto_rainfalls = 67

In [139]:
# Finding Yield
kanto_yield = w1 * kanto_temp+ w3 * kanto_humidity + w2* kanto_rainfalls
kanto_yield

56.2

To perform such calculation for multiple regions, we can use a vector.

In [140]:
# temperature, rainfall, and humidity as a list
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [141]:
#weights as a list
weights = [ w1, w2, w3]

In [142]:
#Function to calculate yield for a region
def crop_yield(region, weights):
    result = 0 
    for i,j  in zip(region, weights):
        result +=(i*j)
    return result 

In [143]:
#what do we have in kanto and weights
for item in zip(kanto, weights):
    print(item)

(73, 0.2)
(67, 0.3)
(43, 0.5)


In [144]:
# Let's check crop yield for kanto
crop_yield(kanto,weights)

56.2

In [145]:
# Similarily let's check for Johto
crop_yield(johto,weights)

76.6

The elementi-wise calculation can also be performed using dot product of two vectors. And we have already learnt, we can do so with numpy array. 
So let's make use of numpy array.

In [146]:
import numpy as np
region_climate_data=np.array([kanto,johto,hoenn,sinnoh, unova])
region_climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [147]:
import numpy as np
weights=np.array(weights)
weights

array([0.2, 0.3, 0.5])

In [148]:
import numpy as np
crop_yield=np.array([])
for i in region_climate_data:
    crop_yield=np.append(crop_yield,sum(i*weights))
crop_yield    

array([56.2, 76.6, 86.6, 51.8, 77.6])

## Practice Example on execution time of numpy array 

In [162]:
# finding crop yielt using climate data array in one line of code
region_climate_data.dot(weights.reshape(3,1))

array([[56.2],
       [76.6],
       [86.6],
       [51.8],
       [77.6]])

In [150]:
# with crop yield function
def crop_yield(region, weights):
    result = 0 
    for i,j  in zip(region, weights):
        result +=(i*j)
    return result 
print(crop_yield(kanto, weights))
print(crop_yield(johto, weights))
print(crop_yield(hoenn, weights))
print(crop_yield(sinnoh, weights))
print(crop_yield(unova, weights))

56.2
76.6
86.6
51.800000000000004
77.6


### Comparison of Execution time
<img src="https://github.com/SimmiSheetalJain/Medias_for_notes_and_blogs/blob/main/numpy_time_comparison.png?raw=true">

## Working with CSV data files

Numpy also provides helper functions reading from & writing to files. Let's download a file `climate.txt`, which contains 10,000 climate measurements (temperature, rainfall & humidity) in the following format:


```
temperature,rainfall,humidity
25.00,76.00,99.00
39.00,65.00,70.00
59.00,45.00,77.00
84.00,63.00,38.00
66.00,50.00,52.00
41.00,94.00,77.00
91.00,57.00,96.00
49.00,96.00,99.00
67.00,20.00,28.00
...
```

This format of storing data is known as *comma-separated values* or CSV. 

> **CSVs**: A comma-separated values (CSV) file is a delimited text file that uses a comma to separate values. Each line of the file is a data record. Each record consists of one or more fields, separated by commas. A CSV file typically stores tabular data (numbers and text) in plain text, in which case each line will have the same number of fields. (Wikipedia)


To read this file into a numpy array, we can use the `genfromtxt` function.
As we have already seen while learning numpy( This is practice section)

In [163]:
import urllib.request 
urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x192d4641850>)

#### open the climate.txt which has gotten downloded in your current jupyter directory you will 10001 records
#### Now, check first line is just a kind of metadata, and rest 10000 are records.

### Now, we can use the genfromtxt function

In [165]:
climate_data=np.genfromtxt('climate.txt',delimiter=',',skip_header=1)

In [167]:
#Let's see the data inside our variable climate_data
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

#### Now, let's find crop yield for all these 10K records

In [171]:
yields = climate_data@weights
print(yields)

[77.3 62.3 63.8 ... 67.4 80.8 68.1]


Let's add this analysis back to the file.<br>
To do so, I will first concatenate this result with the retrieved climate data, and then I can store the data in either a new file or an existing file 

In [175]:
# concatenting with climate data 
crop_yield_analysis= np.concatenate((climate_data, yields.reshape(10000,1)), axis=1)
# records with crop yield analysis 
crop_yield_analysis

array([[25. , 76. , 99. , 77.3],
       [39. , 65. , 70. , 62.3],
       [59. , 45. , 77. , 63.8],
       ...,
       [99. , 62. , 58. , 67.4],
       [70. , 71. , 91. , 80.8],
       [92. , 39. , 76. , 68.1]])

In [176]:
#let's writing back the data using savetxt function
np.savetxt('crop_yield_analysis.txt',
           crop_yield_analysis,
           fmt='%.2f',
           header='temperature,rainfall,humidity,expected_crop_yield',
           comments=' ')

#### now, check in current directory the file crop_yield_analysis.txt and check that it has the expected output