In [5]:
x=int(input("Enter the year"))
if x%4==0 and x%100!=0:
    print(f"{x} is a leap year")
elif x%400==0:
    print(f"{x} is a leap century")
else:
    print(f"{x} is a non-leap year")

Enter the year2525
2525 is a non-leap year


In [25]:
for i in range(6,61,6):
    print(i,end="\t")
    print(i*i)
print("Hi")

6	36
12	144
18	324
24	576
30	900
36	1296
42	1764
48	2304
54	2916
60	3600
Hi


In [26]:
i=2
while i<=20:
    print(i)
    i+=2

2
4
6
8
10
12
14
16
18
20


In [31]:
def factorial(n):
    fact=1
    for i in range(1,n+1):
        fact=fact*i
    

In [34]:
print("Hi")

Hi


3628800

In [1]:
if True:
    print("Inside if block")

Inside if block


In [3]:
a=25;b=5;k=lambda a,b: True if a%b==0 else False;print(k(a,b));print(k(76,18))

True
False


In [4]:
# One line comment
print("Let's Learn commenting")
'''I am a learner,
   a problem solver,
   a teacher,
   a programmer,
   and an analyst '''
print("I wish you a healthy and happy life")

Let's Learn commenting
I wish you a healthy and happy life


In [6]:
def sum_and_product(a,b):
    return (a+b), (a*b)
x,y=sum_and_product(5,4)
print("Sum is : ",x,"\nproduct is : ",y)

Sum is :  9 
product is :  20


In [13]:
home_town = "Agra"
born_and_brought_up = home_town
print(id(home_town),"\n",id(born_and_brought_up))

2742047030064 
 2742047030064


In [16]:
a=35
print(type(a),"\nValue : ",a)
a=3487.894378
print(type(a),"\nValue : ",a)

<class 'int'> 
Value :  35
<class 'float'> 
Value :  3487.894378


In [26]:
import numpy as np
l=list(np.random.randint(23,30,15))
a=[]
list(filter(lambda x: a.append(x) if (x not in a) else None,l))
for i in a:
    print(i)

26
29
23
28
25
24


In [36]:
import numpy as np
from functools import reduce
l=list(np.random.randint(23,30,5))
print(l)
ans=sum(list(filter((lambda x: x if l.index(x)%2==0 else None),l)))
print(ans)

[23, 29, 25, 27, 23]
71


In [46]:
from functools import reduce
l=tuple(np.random.randint(23,30,5))
c=tuple(['a','b','c','d','e'])
res=tuple((i+str(j) for i,j in zip(c,l)))
print(res)

('a23', 'b29', 'c29', 'd28', 'e26')


In [53]:
res=(i*j for i,j in zip(l,(1,2,4,5,6)))
for i in res:
    print(i)

23
58
116
140
156


In [61]:
#sorting a list of tuple 
arr=np.random.randint(2,10,10).reshape(5,2)
arr=tuple(tuple(i) for i in arr)
result=sorted(arr,key=lambda x:x[1])
print(result)

[(2, 2), (8, 4), (4, 7), (9, 9), (8, 9)]


In [66]:
arr=tuple(np.random.randint(2,10,10))
print(arr)
print(tuple(reversed(arr)))

(4, 3, 4, 9, 3, 8, 8, 7, 2, 5)
(5, 2, 7, 8, 8, 3, 9, 4, 3, 4)


In [75]:
set1 = {2, 4, 6, 8}
set2 = {2, 3, 7, 5}
diff=set1.difference(set2)
diff1=set2.difference(set1)
print(diff,diff1)
res=diff.union(diff1)
print(res)

{8, 4, 6} {3, 5, 7}
{3, 4, 5, 6, 7, 8}


In [77]:
set1 = {'apple', 'banana', 'orange'}
set2 = {'orange', 'grape', 'kiwi'}
res=set()
for i in set1:
    for j in set2:
        res.update({i[k:k+3] for k in range(len(j)-2) if i[k:k+3] in j[k:k+3]})
print(res)

{'ora', 'ran', 'ang', 'nge'}


In [79]:
strings = ['hello', 'world', 'python']
suffix = '!'
result=list(map((lambda item: item+suffix), strings))
print(result)


['hello!', 'world!', 'python!']


In [86]:
words = ['python', 'programming', 'language']
words = list(map(lambda x: x.capitalize(),words))
print(words)

['Python', 'Programming', 'Language']


In [88]:
names = ['Alice', 'Bob', 'Charlie', 'Dave', 'Eva']
res=[ i for i in names if i[0] in 'AEIOU']
print(res)

['Alice', 'Eva']


In [93]:
strings = ['abc', '123', 'def456', '789ghi']
res=[ i for i in strings if (any( k.isdigit() for k in i))]
print(res)

['123', 'def456', '789ghi']


In [101]:
import math
numbers = [1, 4, 9, 16, 25, 36, 49]
res=[i for i in numbers if math.sqrt(i)**2==i]
print(res)

[1, 4, 9, 16, 25, 36, 49]


In [104]:
import numpy as np
arr=np.arange(1,7).reshape(2,3)
print(arr)

[[1 2 3]
 [4 5 6]]


In [108]:
arr=np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


 Given two arrays A = [1, 2, 3] and B = [4, 5, 6], perform element-wise addition and subtraction.
    

In [109]:
A=np.array([1, 2, 3])
B=np.array([4, 5, 6])
C=A*B
print(C)
print()

[ 4 10 18]


In [113]:
import numpy as np
array_2d = np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])

res=array_2d[0:3,1:2]
print(res)

[[2]
 [5]
 [8]]


In [114]:
original_array = np.array([[1, 2, 3],
                           [4, 5, 6]])
print(np.transpose(original_array ))

[[1 4]
 [2 5]
 [3 6]]


In [116]:
np.swapaxes(original_array,0,1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [119]:
original_array = np.array([[5, 10],
                           [15, 20],
                           [25, 30]])
i=[]

In [121]:
original_array[original_array%2==0]

array([10, 20, 30])

# Revision (2 Feb 2024)

In [2]:
import keyword as kw
print(kw.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [3]:
a =10 
b = a
print( a is b)

True


In [4]:
print("GATE","CAT","NEET","JEE")

GATE CAT NEET JEE


In [5]:
print("\'Simmi\' is alias for Sheetal")

'Simmi' is alias for Sheetal


# the eval function 

In [ ]:
cont. tomo